### ISSUE TITLE
[Bug]: serwist tries to install service worker with different name than specified in next config

### ISSUE THREAD

**Issue by mturczyn** [serwist/serwist#103]
### Provide environment information

 "@serwist/next": "^8.4.4",
 "@serwist/precaching": "^8.4.4",
 "@serwist/sw": "^8.4.4",

I also have such next.js config
```
import withPWAInit from '@serwist/next'

/** @type {import('next').NextConfig} */
const withPWA = withPWAInit({
    swSrc: 'app/service-worker.ts',
    swDest: 'public/service-worker.js',
})

const nextConfig = { output: 'standalone' }

export default withPWA(nextConfig)
```

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/mturczyn/about-intrinsic-nextjs/blob/main/next.config.mjs

### To reproduce

Setup next.js project with serwist and use `service-worker.js` as destination file.

### Describe the bug

I expect for it to work seamlesly, however I keep getting following error in browser:
> DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/sw.js'): The script has an unsupported MIME type ('text/html').

As shown, it still tries to get `sw.js` file. 

However, service worker JavaScript file was correctly generated in `public` directory.

After just changing `swDest: 'public/service-worker.js'` to `swDest: 'public/sw.js'` solved the issue:

![image](https://github.com/serwist/serwist/assets/11062920/a1c05d1a-0aef-4743-ad19-3b157731b435)

Also, I have noticed, when I changed `swDest` file name, previously generated JS file was not removed and I guess, as "compilation"/parsing output, it should be cleaned automatically.

### Expected behavior

I can specify whatever file name for service worker and all should be wired up by `serwist`

I can freely change name of service worker in next.js config file, and not keep all previous files with different file names - if i change name for service worker file, somehow old file should be cleaned.

### Screenshots (if relevant)

Successfull service worker installation

![image](https://github.com/serwist/serwist/assets/11062920/b11968a7-48f9-4a79-81d5-c5f0870ef128)

**Comment by DuCanhGH** [comment]
Use `swUrl`.

**Comment by mturczyn** [comment]
Right....
I just read it. Thanks
