### ISSUE TITLE
[Bug]: Logs spammed on console in production

### ISSUE THREAD

**Issue by mathewcst** [serwist/serwist#111]
### Provide environment information

NextJS 14.1

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://lostark.party/

### To reproduce

Created a NextJS app and used the following setting:

```ts
import { defaultCache } from "@serwist/next/browser";
import { installSerwist } from "@serwist/sw";

import type { PrecacheEntry } from "@serwist/precaching";

declare const self: ServiceWorkerGlobalScope & {
  // Change this attribute's name to your `injectionPoint`.
  __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
};

// Anything random.
const revision = crypto.randomUUID();

installSerwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: defaultCache,
  disableDevLogs: true,
  fallbacks: {
    entries: [
      {
        url: "/~offline",
        revision,
        matcher({ request }) {
          // Or whatever else you want to check for in a request.
          return request.destination === "document";
        },
      },
    ],
  },
});

```

### Describe the bug

Although `disableDevLogs` is set to true, on production, the app spams console logs with serwist info

### Expected behavior

To not have any logs on production

### Screenshots (if relevant)

![image](https://github.com/serwist/serwist/assets/5620645/2e7bc611-6700-41d1-bc36-6e134aa69cfd)

### Additional information (if relevant)

Can be viewed on: https://lostark.party

**Comment by mathewcst** [comment]
Found a `mode` on withSerwistInit, although setting it to production the problem presists.

```ts
const withSerwist = withSerwistInit({
  cacheOnFrontEndNav: true,
  swSrc: "src/sw.ts",
  swDest: "public/sw.js",
  swUrl: "/sw.js",
  reloadOnOnline: true,
  mode: "production",
  exclude: [
    /\/.*.(js|css).map\//,
    /\.map$/,
    /^manifest.*\.js$/,
    "/api/event",
    "/js/script.js",
  ],
  additionalPrecacheEntries: [],
  disable: process.env.NODE_ENV === "development",
});

```

**Comment by mathewcst** [comment]
Ok, found the problem, we can close this now.

Somehow I uploaded a `sw.js` built in development to production.

**Comment by DuCanhGH** [comment]
@mathewcst 💀

How is that supposed to happen...

Also, `mode` doesn't do anything and will be gone in v9.0.0 :)
