### ISSUE TITLE
[Bug]: Browser export missing from NextJS package

### ISSUE THREAD

**Issue by mikeproeng37** [serwist/serwist#117]
### Provide environment information

Using: 

- `@serwist/next@9.0.0-preview.21`
- `Nodev21.7.2`

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

Sorry no link, just some screenshots

### To reproduce

I've followed all the instructions from https://serwist.pages.dev/docs/next/getting-started including adding the ts typings in my `tsconfig.json`. 

### Describe the bug

Hi, I am getting this issue with the `defaultCache` import on my `sw.ts`

![image](https://github.com/serwist/serwist/assets/1365958/14937827-2063-45a7-884c-211837d99281)

Get the same issue when I run `next build`. 

Upon inspecting `/node_modules/@serwist/next/package.json` it looks like the browser export is indeed missing:

![image](https://github.com/serwist/serwist/assets/1365958/8a46ce66-3c81-47c9-9d85-ea420b212e03)

### Expected behavior

I expect `next build` command to run successfully.

### Screenshots (if relevant)

![image](https://github.com/serwist/serwist/assets/1365958/1549ac1d-3376-491e-a672-c814286f459c)

**Comment by YO-SC** [comment]
use `import { defaultCache } from '@serwist/next/worker'`

**Comment by mikeproeng37** [comment]
> You should use [the preview docs](https://9-0-0.serwist.pages.dev) instead of the stable one. By the way, in 9.0.0, that export got renamed to /worker.

Thanks this did it! Will close out issue now.
