### ISSUE TITLE
[Bug]: When using serwist/next with pyodide/webpack-plugin - "TypeError: The 'compilation' argument must be an instance of Compilation"

### ISSUE THREAD

**Issue by type9** [serwist/serwist#119]
### Provide environment information

With Next 14.03

├─┬ @pyodide/webpack-plugin@1.3.2 overridden
│ └─┬ copy-webpack-plugin@11.0.0
│   └── webpack@5.91.0 deduped
├─┬ @serwist/next@9.0.0-preview.21
│ └─┬ @serwist/webpack-plugin@9.0.0-preview.21
│   └── webpack@5.91.0 deduped
└─┬ file-loader@6.2.0
  └─┬ webpack@5.91.0
    └─┬ terser-webpack-plugin@5.3.10
      └── webpack@5.91.0 deduped

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

N/A

### To reproduce

1. Attempt to configure webpack like so for Pyodide and Serwist

```mjs
//next.config.mjs
import { PyodidePlugin } from "@pyodide/webpack-plugin"
import withSerwistInit from "@serwist/next"

const withSerwist = withSerwistInit({
	swSrc: "app/sw.ts",
	swDest: "public/sw.js",
})

/** @type {import('next').NextConfig} */
export default withSerwist({
	webpack: (config, { isServer }) => {
		if (!isServer) {
			config.plugins.push(new PyodidePlugin())
		}
		if (isServer) {
			config.externals = ["pyodide", ...(config.externals || [])]
		}
		return config
	},
})

```
2. Attempt to `npm run dev` for it to fail with logs
```log
TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/Users/gabriel/dev/colorchordsapp/node_modules/webpack/lib/NormalModule.js:241:10)
    at file:///Users/gabriel/dev/colorchordsapp/node_modules/@pyodide/webpack-plugin/plugin.mjs:314:99
    at Hook.eval [as call] (eval at create (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:13:28645), <anonymous>:122:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:13:25915)
    at Compiler.newCompilation (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:28:147694)
    at /Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:28:148481
    at Hook.eval [as callAsync] (eval at create (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
    at Compiler.compile (/Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:28:148407)
    at /Users/gabriel/dev/colorchordsapp/node_modules/next/dist/compiled/webpack/bundle5.js:28:489605
```
3. Searching online for the error and realize it's typically caused by multiple webpack dependencies of different version
4. Run `npm dedupe` to rerun and see same error

### Describe the bug

Apologies I'm new to webpack configurations and webworkers but I'm trying to use Serwist to handle the caching of Pyodide's large wasm .whl/.zip files it needs to serve to the client.

Notably Pyodide's support of Next.js and similar frameworks is circumstantial at best but I've gotten it to work well with enough fiddling. Pyodide team provides a webpack-plugin for itself due to an errors like such that will happen:
```log
Module build failed: UnhandledSchemeError: Reading from "node:child_process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:child_process
./node_modules/pyodide/pyodide.mjs
./scripts/pyodide/PyodideManager.ts
./scripts/hooks/usePyodide.ts
./inputs/providers/CompanionContextProvider/CompanionContextProvider.tsx
./inputs/providers/CompanionContextProvider/index.tsx
./components/LiveCompanion/LiveCompanionView/LiveCompanionView.tsx
```

I'm not sure if someone here would know if this is something that can be worked around. Thanks in advance.

### Expected behavior

`npm run dev` starts up without issue

**Comment by type9** [comment]
Hi @DuCanhGH thank you so much for the thorough response. I agree it seems to be a result of nextjs having its own proprietary version of webpack.

Just briefly would you by chance have any leads of workarounds I can look into? I'm not familiar enough with webpack. Otherwise I'll look for a temporary workaround until nextjs can fix it on their end.

Just fyi,
I do see your plugin being crucial to any python + nextjs project as wasm.whl files can be very large and at least in chrome does not disk cache so webworkers would be essential here.

**Comment by DuCanhGH** [comment]
@type9 a fast and dirty workaround would be to patch the plugin so that it uses `compiler.webpack`. I'm not really familiar with `patch-package`, the `pnpm patch` of npm, however, so I can't tell you the specifics, and you will need to take a look at its documentation.

**Comment by type9** [comment]
awesome that worked perfectly!
I used `npm install patch-package postinstall-postinstall`

and replaced line:314 like so for future reference of anyone else running into the same issue. I'll make an issue under next and pyodide to get a solid fix
```json
//package.json
"scripts": {
  "postinstall": "patch-package"
}
```

```mjs
//@pyodide/webpack-plugin/plugin.mjs
const compilationHooks = compiler.webpack.NormalModule.getCompilationHooks(compilation);
```

**Comment by type9** [comment]
Hi @DuCanhGH . Apologies for bugging you again but I've been trying to solve the integration of pyodide + serwist  all day and I think I'm one more step from having it figured out.

I have it working in a development environment, but in production Pyodide tries to call a url that throws an error stopping the service worker from finishing the installation. I'm pretty sure this is another quirk of semi-support from pyodide-webpack-plugin but I'm hoping to solve without another patch.

<img width="985" alt="Screenshot 2024-04-13 at 10 43 20 PM" src="https://github.com/serwist/serwist/assets/38086758/da66084e-84c8-43b9-987a-d22fb4bb35fd">

I have tried to redirect it to the proper url using but when I logged it I noticed this manipulator does not fire before precache throws the error in prod.
```ts
const pyodideRegex = /^\/_next\/pyodide\/(.*)$/
const urlManipulator: UrlManipulation = ({ url }) => {
	// Check if the URL pathname matches the pattern
	const match = url.pathname.match(pyodideRegex)
	if (match) {
		const newPath = `${PYODIDE_LOCATION}/pyodide/${match[1]}`
		return [new URL(newPath)]
	}

	return []
}
```
<img width="565" alt="Screenshot 2024-04-13 at 10 54 55 PM" src="https://github.com/serwist/serwist/assets/38086758/42c65299-67ef-4b22-8a55-902de715a872">

**I wanted to ask if there's a way I can catch this precache attempt before it fires or if I can stop a failed precache from halting the install of the sw.js**

Here is the full sw.ts if your reference. Thanks in advance!
```ts
import { defaultCache } from "@serwist/next/worker"
import type {
	PrecacheEntry,
	RuntimeCaching,
	SerwistGlobalConfig,
	UrlManipulation,
} from "serwist"
import { CacheFirst } from "serwist/strategies"
import { ExpirationPlugin } from "serwist/plugins"
import { Serwist } from "serwist"

const PYODIDE_LOCATION = `${process.env.NEXT_PUBLIC_VERCEL_BLOB_URL}/pyodide/${process.env.NEXT_PUBLIC_PYODIDE_VERSION}`
const PYTHON_PACKAGE_LOCATION = `${process.env.NEXT_PUBLIC_VERCEL_BLOB_URL}/python-packages`
const pyodideRegex = /^\/_next\/pyodide\/(.*)$/

declare global {
	interface WorkerGlobalScope extends SerwistGlobalConfig {
		// Change this attribute's name to your `injectionPoint`.
		// `injectionPoint` is an InjectManifest option.
		// See https://serwist.pages.dev/docs/build/inject-manifest/configuring
		__SW_MANIFEST: (PrecacheEntry | string)[] | undefined
	}
}

declare const self: ServiceWorkerGlobalScope

const runtimeCache: RuntimeCaching[] = [
	...defaultCache,
	{
		matcher: new RegExp(`${PYODIDE_LOCATION}/.*`),
		handler: new CacheFirst({
			cacheName: `pyodide-packages`,
			plugins: [
				new ExpirationPlugin({
					maxEntries: 20,
					maxAgeSeconds: 365 * 24 * 60 * 60, // One year
				}),
			],
		}),
	},
	{
		matcher: new RegExp(`${PYTHON_PACKAGE_LOCATION}/.*`),
		handler: new CacheFirst({
			cacheName: "python-packages",
			plugins: [
				new ExpirationPlugin({
					maxEntries: 50,
					maxAgeSeconds: 365 * 24 * 60 * 60, // One year
				}),
			],
		}),
	},
]

const urlManipulator: UrlManipulation = ({ url }) => {
	// Check if the URL pathname matches the pattern
	const match = url.pathname.match(pyodideRegex)
	if (match) {
		const newPath = `${PYODIDE_LOCATION}/pyodide/${match[1]}`
		return [new URL(newPath)]
	}

	return []
}

const serwist = new Serwist({
	precacheEntries: self.__SW_MANIFEST,
	skipWaiting: true,
	clientsClaim: true,
	runtimeCaching: runtimeCache,
	navigationPreload: true,
	precacheOptions: {
		urlManipulation: urlManipulator,
	},
})

serwist.addEventListeners()
```

**Comment by DuCanhGH** [comment]
@type9 `precacheOptions.urlManipulation` is used when handling requests, not precaching :) To change the invalid URL to the actual URL, you should use `withSerwistInit`'s `manifestTransforms` instead. If you want to exclude the asset altogether, you can also use `withSerwistInit`'s `exclude`.

**Comment by type9** [comment]
@DuCanhGH thanks for the amazing responses! I was able to get it working on prod using transforms exactly as you said.

Reference below for those who might need it.
```ts
manifestTransforms: [
			//workaround for pyodide location caused by pyodide-webpack-plugin requesting an invalid url
			async (manifestEntries) => ({
				manifest: manifestEntries.map((manifestEntry) => {
					const nextPyodideMatch =
						manifestEntry.url.match(pyodideRegex)
					if (nextPyodideMatch) {
						return {
							...manifestEntry,
							url: `${PYODIDE_LOCATION}/${nextPyodideMatch[1]}`,
						}
					}
					return manifestEntry
				}),
			}),
		],
	})
```

Yes as somehow who's not that familiar with these APIs I would say I was sidetracked as a result naming though I see how it might be obvious to those who have worked with service workers before.

As an additional note I'm thinking about creating a package for using pyodide in a react framework environment like next as I've had to jump through a lot of hoops to get it working without significant compromise. I think a result of the webassembly package sizes I expect serwist to be a cornerstone of this package.

I will probably end up writing documentation to keep track of the current workarounds and standardize the process there from the perspective of those who don't touch this realm of web-tech very often. If you like I can send you what I write when I get to it and you can pull from it what you like to embellish the serwist docs for those less technical. Let me know if this is useful for serwist. Thanks again!

**Comment by DuCanhGH** [comment]
@type9

> I will probably end up writing documentation to keep track of the current workarounds and standardize the process there from the perspective of those who don't touch this realm of web-tech very often. If you like I can send you what I write when I get to it and you can pull from it what you like to embellish the serwist docs for those less technical. Let me know if this is useful for serwist. Thanks again!

Well, do let me know if you can come up with ways to make the Serwist docs more welcoming to newcomers :D I'm really struggling with the docs, with it being the only thing holding the 9.0.0 release down. Congrats on solving the issue! Here's to a future successful package :)
