### ISSUE TITLE
How Can I cache resources from my application to have complete offline feature?

### ISSUE THREAD

**Issue by elVengador** [serwist/serwist#135]
I'm implementing a complete offline application, I dont want to display a fallback page when there is not internet
I want to cache all my files `.html, .js, .css, .png, and font families`
When there is not internet I want my application check the cache and use it

That set up was posible in an old version of NextJs with next-pwa, but now I'm updating my application and I want to use serwist

Thanks in advance 🙏

**Comment by DuCanhGH** [comment]
https://serwist.pages.dev/docs/serwist/guide/precaching

https://serwist.pages.dev/docs/serwist/runtime-caching
