### ISSUE TITLE
[Docs]: Getting started page is missing instructions for installing @serwist/precaching and @serwist/sw

### ISSUE THREAD

**Issue by elsigh** [serwist/serwist#14]
### Provide environment information

I visited https://serwist.pages.dev/docs/next/getting-started

### Describe the problem

At Step 2 - creating sw.ts - VSCode noticed that there are imports for @serwist/precaching and @serwist/sw but I hadn't yet installed those (Step 1 missed them)

### Expected behavior

Step 1 should be complete

### Additional information (if relevant)

Once I installed those two packages my errors went away

**Comment by DuCanhGH** [comment]
![image](https://github.com/serwist/serwist/assets/75556609/36d06ec7-17eb-41d3-8978-ac563b3a708b)
Fixed :) Thanks for reporting!
