### ISSUE TITLE
Question: Is there a way to disable the precaching?

### ISSUE THREAD

**Issue by robert-barahona** [serwist/serwist#143]
Hi, I would like to know if there is a way to disable the precaching in serwist/next?

**Comment by DuCanhGH** [comment]
Use `exclude: [() => true]`. This is the only way to achieve that in `@serwist/next`. In the future, we may expose the `disablePrecacheManifest` option again though.

Also, next time, if you have a question, please open a new discussion rather than an issue.

Hope this helps!

**Comment by robert-barahona** [comment]
I did that, but didn't work, I still seeing all the resources being downloaded in the first load of the page 😕... I managed to disable the precaching with this code:

```
...
self.__SW_MANIFEST

const serwist = new Serwist({
  precacheEntries: [],
...
```

**Comment by DuCanhGH** [comment]
@robert-barahona ah, right, you also need `additionalPrecacheEntries: []`...

Hopefully we can sort the weird mess in `@serwist/next` out in v10...

**Comment by robert-barahona** [comment]
thank you! that worked
