### ISSUE TITLE
[Docs]: Build fails if you follow setup guide Next.js

### ISSUE THREAD

**Issue by JesseKoldewijn** [serwist/serwist#144]
### Provide environment information

not required, is applicable to setup of serwist inside existing and new Next.js applications that use Typescript

### Describe the problem

The lack of mentioning the need to exclude the swe output and sw inside your tsconfig results in failing builds with unclear error messages (messages come from next themselves so the precise message is unrelated to issue at hand)

### Expected behavior

It might be useful to note the exclusion of the output files (which get dropped inside the public folder on build) inside the tsconfig/jsconfig (if applicable), eslint config (just for good measure) and inside your gitignore.

**Comment by DuCanhGH** [comment]
Ah, yeah, will fix the docs later! Thanks for noticing.

**Comment by DuCanhGH** [comment]
I've fixed this as [can be seen here](https://serwist.pages.dev/docs/next/getting-started#updating-tsconfig)! Closing this issue.
