### ISSUE TITLE
[Bug]: Preload config error

### ISSUE THREAD

**Issue by dalist1** [serwist/serwist#146]
### Provide environment information

The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

### Which project is this issue for?

serwist

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

.

### To reproduce

Error comes out from this config seems like:

const serwist = new Serwist({
    precacheEntries: self.__SW_MANIFEST,
    skipWaiting: true,
    clientsClaim: true,
    navigationPreload: true,
    runtimeCaching: defaultCache,
})

### Describe the bug

Add the above config, and check the console.

### Expected behavior

No error is supposed to come up in the console, not sure where the issue exactly lies, here's my nextjs info:

Operating System:
  Platform: linux
  Arch: x64
  Version: #202404301715 SMP PREEMPT_DYNAMIC Tue Apr 30 17:56:17 UTC 2024
  Available memory (MB): 64042
  Available CPU cores: 16
Binaries:
  Node: 21.7.3
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.1.1
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 15.0.0-rc.0
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A 

### Screenshots (if relevant)

.

### Additional information (if relevant)

.

**Comment by DuCanhGH** [comment]
@dalist1 huh, not sure how that can happen with `defaultCache`. Serwist always handles preloaded responses when intercepting network requests.

It may be the case that some navigation requests got through the service worker (i.e when no route matches the request), resulting in the preloaded responses being discarded. You may add `serwist.setDefaultHandler` to check this.

**Comment by gsemyong** [comment]
Having the same issue. It does appear that page is getting preloaded correctly in a production build though.

**Comment by DuCanhGH** [comment]
@gsemyong ah...

In development mode, `defaultCache` is set to `undefined`. This causes all requests to not be handled by the service worker, resulting in the preloaded responses being discarded. Well, I guess we could add a fallback `NetworkFirst` strategy for `defaultCache` there then.

**Comment by gsemyong** [comment]
@DuCanhGH I've changed the snippet to be
```ts
const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching:
    defaultCache.length === 0
      ? [
          {
            matcher: () => true,
            handler: new NetworkFirst(),
          },
        ]
      : defaultCache,
});
```
Seems like the warnings are gone. Is that what you meant?

**Comment by DuCanhGH** [comment]
@gsemyong ...yep. That's what I meant.

**Comment by dalist1** [comment]
guys, I haven't had time to play around with this recently but will definitely try the networkFirst fallback strategy out later.

thanks @gsemyong 

> @DuCanhGH I've changed the snippet to be
> 
> ```ts
> const serwist = new Serwist({
>   precacheEntries: self.__SW_MANIFEST,
>   skipWaiting: true,
>   clientsClaim: true,
>   navigationPreload: true,
>   runtimeCaching:
>     defaultCache.length === 0
>       ? [
>           {
>             matcher: () => true,
>             handler: new NetworkFirst(),
>           },
>         ]
>       : defaultCache,
> });
> ```
> 
> Seems like the warnings are gone. Is that what you meant?

**Comment by coderfin** [comment]
I am getting this error even in production mode.  I tried changing the `runtimeCaching` option as suggested but it didn't make a difference.  As long as I have `navigationPreload: true` I get the error.  Any other thoughts or updates on this?

**Comment by DuCanhGH** [comment]
@coderfin this is where we use `event.preloadResponse`:

https://github.com/serwist/serwist/blob/d677eede50de2827cf01cf027d4694574efc0f2e/packages/core/src/lib/strategies/StrategyHandler.ts#L134-L142

When Serwist handles a request that triggers the error, does it reach this point? What does the if branch return?

**Comment by coderfin** [comment]
@DuCanhGH It never gets inside the `if` statement.  `request.mode` is always `cors` when I check.

I do have additional information.

My project is a NextJS project.
I only see the error when running in production.
I only see the error when I set `serwist.addToPrecacheList` or `additionalPrecacheEntries`.
I only see the error on a page that has been included in the precache entries.
I only see the error on the second refresh after the service worker has had a chance to register.

My current next.config.js contains:
```ts
const serwist = serwistInit({
  additionalPrecacheEntries: [
    {
      url: '/',
      revision,
    },
    {
      url: '/about',
      revision,
    },
  ],
  cacheOnNavigation: true,
  swDest: 'public/service-worker.js',
  swSrc: 'src/service-worker.ts',
  swUrl: 'service-worker.js',
})
```
My current `service-worker.ts` contains:
```ts
const serwist = new Serwist({
  clientsClaim: true,
  navigationPreload: true,
  precacheEntries: self.__SW_MANIFEST,
  runtimeCaching: defaultCache,
  skipWaiting: true,
})
```

Here is an example.  I build my project for production and start it.  I ensure that my application storage has been cleared in the browser (all caches cleared and service worker unregistered).  I visit `/about`.  Everything is fine, the service worker gets registered, and the caches get created.  I refresh the `/about` page.  I see the error.  If I remove `additionalPrecacheEntries`, leave everything else as is, and follow the same flow I do not see the error.

**Comment by DuCanhGH** [comment]
@coderfin wait...

When you add "/about" to your precache list, Serwist will use `PrecacheStrategy` when handling requests to the page, which means that we never reach the part where Serwist uses `event.preloadResponse`. The request with `request.mode` set to `"cors"` is probably an unrelated thing.

To temporarily fix this, remove those pages from `additionalPrecacheEntries` and add this to your service worker:

```ts
const serwist = new Serwist(options);

const urlsToPrecache = ["/", "/about"] as const;

self.addEventListener("install", (event) => {
  const requestPromises = Promise.all(
    urlsToPrecache.map((entry) => {
      return serwist.handleRequest({ request: new Request(entry), event });
    }),
  );

  event.waitUntil(requestPromises);
});

serwist.addEventListeners();
```

I guess we will have to make `PrecacheStrategy` account for situations where `navigationPreload` is enabled as well.

**Comment by coderfin** [comment]
@DuCanhGH Thank you for your help!  Your explanation is appreciated;  it helps me to understand better what is going on and is very reassuring.  I implemented the fix that you suggested and it works!  The error no longer shows and the pages are correctly pre-cached.

I kinda like that it is using `the strategies of the routes that match them` instead of the `PrecacheStrategy`.  With my currently limited knowledge and searching I couldn't see a way, for example, to set `matchOptions` for the pre-cached pages.  With this update, if I'm not mistaken, it will use any `matchOptions` in the strategy that matches the route.

**Comment by DuCanhGH** [comment]
@coderfin wait...

Seems that I forgot to allow setting `fetchOptions` and `matchOptions` in the `Serwist` class. Oops! Will fix soon :)
