### ISSUE TITLE
[Docs]: Install button not showing up in browser url bar after following serwist next instructions

### ISSUE THREAD

**Issue by jonericcook** [serwist/serwist#147]
### Provide environment information

```
  "dependencies": {
    "@serwist/next": "^9.0.2",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "postcss": "^8",
    "serwist": "^9.0.2",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
```

### Describe the problem

I followed the nextjs install instructions here https://nextjs.org/docs/getting-started/installation

I followed the serwist/next instructions here https://serwist.pages.dev/docs/next/getting-started

On step 4 of your instructions I read "Update app/manifest.json (App Router) or public/manifest.json (Pages Router) with the following content:" should the manifest.json file be in the public folder not matter what nextjs app structure is used?

My code base is here https://github.com/jonericcook/hello

When I i run the app via npm run dev I do not see the install button in the url bar.

### Expected behavior

I see the install button in the url bar

### Additional information (if relevant)

I did find this example https://github.com/serwist/serwist/tree/main/examples/next-basic where the manifest.json is in the public folder.

I found this article https://javascript.plainenglish.io/building-a-progressive-web-app-pwa-in-next-js-with-serwist-next-pwa-successor-94e05cb418d7 where he uses a manifest.ts file https://github.com/uriseroussi/next-serwist-pwa-example/blob/main/src/app/manifest.ts and his app works as expected.

**Comment by DuCanhGH** [comment]
No, app/manifest.json is right for App Router users.

Please ensure that your app web manifest is valid. For example, check if all the icons specified in it are available.

**Comment by jonericcook** [comment]
that was it - i didnt have the icons stated in the manifest
