### ISSUE TITLE
[Bug]: next-web-push example not working

### ISSUE THREAD

**Issue by wnz99** [serwist/serwist#149]
### Provide environment information

node v18 on macOs 14.5 

"@serwist/next": "latest",
"next": "14.2.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"serwist": "latest",
"web-push": "3.6.7"

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/serwist/serwist/tree/main/examples/next-web-push

### To reproduce

Run the following command `npx degit serwist/serwist/examples/next-web-push my-app` and follow the other instruction to complete the installation at https://github.com/serwist/serwist/tree/main/examples/next-web-push

### Describe the bug

Hi, 

I tried to run the next web push example here by running the `npx degit serwist/serwist/examples/next-web-push my-app` command and following the other instructions:

https://github.com/serwist/serwist/tree/main/examples/next-web-push

However, it is now working for me. Notifications are not showing. 

Could you please confirm whether it's just my problem?

Similarly, I've tried this other example from https://github.com/shadowwalker/next-pwa/tree/master/examples/web-push and it works as expected.

### Expected behavior

Notifications should appear.

**Comment by DuCanhGH** [comment]
I forgot to subscribe the service worker to the `push` event... Really sorry about this...

**Comment by mbj36** [comment]
@DuCanhGH I still can't see the notification on browser
