### ISSUE TITLE
[Docs]: Next.js app router allows use of manifest.ts

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [serwist/serwist#152]
### Provide environment information

As stated [here](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/manifest) Next.js provides the ability to use a manifest.ts file instead of a manifest.json file.

An example of the use of such a file is here:

https://github.com/FleetAdmiralJakob/chat-io/blob/main/src/app/manifest.ts

### Describe the problem

The support of ts files in stuff like autocompletion and errors is much better than the things provided in IDEs for JSON

### Expected behavior

There are two options:

1. Recommend the use of a ts file in app router over json

2. Note that the use of a ts file can have many benifits

**Comment by DuCanhGH** [comment]
I don't see the purpose for diverging from the standards here, especially when `$schema` exists. Ultimately, we don't want to introduce too many framework-specific concepts into the documentation, lest the user gets confused when they switch from a framework to another. Their knowledge should apply from one place to another whenever that's possible in my opinion. You should use what you prefer, though.
