### ISSUE TITLE
[Docs]:  ExpirationPluginOptions docs/functionality inconsistencies

### ISSUE THREAD

**Issue by jon-smith** [serwist/serwist#154]
### Provide environment information

`@serwist/next` v9.0.2

### Describe the problem

After working with the expiration plugin, I think I've found some inconsistencies between the docs and functionality, or at least things that caused confusion for me.

In my case I'm using:

```
new ExpirationPlugin({
	maxEntries: [some integer],
	maxAgeSeconds: undefined
});
```

From the docs (and comments):
> `maxEntries` — The maximum number of entries to cache. Entries used least recently will be removed as the maximum is reached.

However this only appears to apply if `maxAgeFrom` is set to `last-used`, but the default is `last-fetched`. Furthermore, `maxAgeFrom` isn't present in the docs and the comment in the code indicates it only applies to `maxAgeSeconds`:

```
// ExpirationPlugin.ts
/**
   * Determines whether `maxAgeSeconds` should be calculated from when an
   * entry was last fetched or when it was last used.
   *
   * @default "last-fetched"
   */
  maxAgeFrom?: "last-fetched" | "last-used";
```

### Expected behavior

I'm happy with how it works when I set `maxAgeFrom: 'last-used'`, but I'm not sure whether the functionality or documentation is correct. If someone can clarify I could take a look at making a PR

**Comment by DuCanhGH** [comment]
Ah yes, that was me forgetting to update its documentation!

Thank you for noticing! This will be fixed in 9.0.3.
