### ISSUE TITLE
[Docs]: Testable dev server

### ISSUE THREAD

**Issue by sventies** [serwist/serwist#157]
### Provide environment information

To test the offline functionality, I go to Network in the chrome devtools and select "offline". Unfortunately, this breaks my app while using the dev server. 

### Describe the problem

So I haven't found a way to properly test the offline-first functionality while using the dev-server.
However, if I build the app and start a production server, as well as actually deploying the app to vercel, the offline functionality works great!

Have I missed something about the dev server, is there maybe a fundamental reason in how service workers work, that this cannot be tested properly in dev?

### Expected behavior

Dev server to produce the same caching behavior as prod

**Comment by DuCanhGH** [comment]
You see, if we were to cache something, you would always see a stale version of your application. For example, if your JS scripts were to be handled by `StaleWhileRevalidate`, it would take one additional reload to see the updated version, which is obviously not the desired behaviour in dev mode. Or if they were to be handled by `CacheFirst`, you would never see updated versions of them. As such, in dev mode, `defaultCache` tells Serwist to handle every request with `NetworkOnly` to prevent such situations. Of course, you can overwrite this by creating a custom `runtimeCaching` array.

**Comment by sventies** [comment]
Thanks a lot, that makes sense. 

I wonder if it’s clear enough from the getgo, for people who are just getting started with service workers. I personally struggled a bit before finding this out, but that’s n=1. 

For now I can work with testing the build rather than in dev mode, if I want to test offline-first functionality.

If you find that more beginners are struggling, let me know, maybe I can help make some content for noobs like me :)
