### ISSUE TITLE
[Docs]: Add `gitignore` options to docs

### ISSUE THREAD

**Issue by elie222** [serwist/serwist#161]
### Provide environment information

Environment not relevant

### Describe the problem

Unclear from docs what should be in the `.gitignore`.

### Expected behavior

Show this for the `.gitignore` somewhere in the docs:

```
# Serwist
**/public/serwist**
**/public/sw**
**/public/worker**
**/public/fallback**
**/public/precache**
```

### Additional information (if relevant)

Here is where I found what to put in my `.gitignore`:
https://github.com/serwist/serwist/blob/main/examples/next-basic/.gitignore#L39C1-L44C21

**Comment by DuCanhGH** [comment]
@elie222 ah yes. Thanks for reminding me!
