### ISSUE TITLE
[Docs]: Handling third party libraries

### ISSUE THREAD

**Issue by standingdreams** [serwist/serwist#164]
### Provide environment information

Using Magicbell to provide notifications in a NextJS application.

### Describe the problem

In order to receive push notifications, you must provide `importScripts("https://assets.magicbell.io/web-push-notifications/sw.js")` inside of `public/sw.js`. There currently is no clear definition of handling third party libraries. I imagine that I must utilize `additionalPrecacheEntries` but I have not been successful in making it work properly.

### Expected behavior

Ability to utilize third party libraries like Magicbell that require a `sw.js`. There is no clear directions of how to either add `importScripts` to the `sw.js` file that Serwist generates or to add the contents of https://assets.magicbell.io/web-push-notifications/sw.js to the Serwist build process.

**Comment by DuCanhGH** [comment]
...Just add `importScripts("https://assets.magicbell.io/web-push-notifications/sw.js")` to your SW source.

**Comment by standingdreams** [comment]
Thank you, @DuCanhGH. I appreciate all your work on Serwist as well.

This seems obvious, but for someone new to service workers, it can be a daunting task. It would be great to have a section in the documentation that addresses libraries and/or `importScripts` for the destination `sw.js` file.

**Comment by DuCanhGH** [comment]
@standingdreams eh, I figured that the users would seek MDN/web.dev for more documentation on things. That's why we don't document built-in features the likes of `importScripts` - the point is that people would have to go to the exact place to learn more about them and (service) workers in general. I think the balance is just right :)

**Comment by standingdreams** [comment]
I can understand that. I'll close this.
