### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by ZackTRobertson** [serwist/serwist#170]
### Which project is this feature request for?

serwist

### Describe the feature you'd like to request

First, thanks for all your work on this project. I'm wondering if there is a way to use the ExpirationPlugin with the handler.fetchAndCachePut method when called inside a Strategy Handler.

### Describe the solution you'd like

I'd like to be able to pass an ExpirationPlugin tothe fetchAndCachePut as an argument along with the request object as an optional parameter:

handler.fetchAndCachePut(request, myExpirationPlugin);

### Describe alternatives you've considered

If there is already a better way to achieve this then perhaps make a note of it in the Strategy Handler section. Basically, I have some logic I'd like to run on every request, and if the asset is no longer in the cache I need to fetch it with certain expiration options.

**Comment by DuCanhGH** [comment]
You usually pass the plugin to your `Strategy`'s constructor, and then the `Strategy` instance will use the `StrategyHandler` class by itself.

**Comment by ZackTRobertson** [comment]
Thanks for the quick reply. That is what I was doing, and I was able to set the cache name correctly. But for some reason the expiration plugin isn't working on the fetch and cache. I'll play around with it a little more and see if it was an error on my side. If I can't get it working, I'll raise an issue with more details.
