### ISSUE TITLE
[Question] Pre-cache page & fallback

### ISSUE THREAD

**Issue by guidovizoso** [serwist/serwist#171]
Hi! First of all, thank you for creating Serwist and helping us all with bringing PWA support for Next!

I have this project with Next 14 that is supposed to have offline capabilities. Once the user is logged in I'm supposed to save some properties (I can use Indexed DB, local storage or any other approach), but the tricky part is: I have to show the user a page with a form, let's call it `/report/new` even if offline, that populates some options from the user profile and allow the user to navigate to that page. On the other pages It's completely fine to only show the application shell (header and nav) with a message stating that there is no internet connection. 

I currently have this Next config:
```ts
const withSerwist = withSerwistInit({
  swSrc: "src/app/sw.ts",
  swDest: "public/sw.js",
  reloadOnOnline: false,
  cacheOnNavigation: true,
});
```

And this is my service worker:
```
const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching:
    defaultCache.length === 0
      ? [
          {
            matcher: () => true,
            handler: new NetworkFirst(),
          },
        ]
      : defaultCache,
});

serwist.addEventListeners();
```

I also created a ServiceWorker component that I call form my main layout, it currently has the Indexed DB functionality (which give or take works fine) and a useEffect to display an indicator if my app is offline.

I'm not entirely sure if my approach is correct and what would be the best way to pre-cache this form page (which then I'll have to populate with some local data).

Is there a best approach to obtaining something like that with Serwist out of the box?

Thanks in advance!

**Comment by DuCanhGH** [comment]
This workaround:

```
runtimeCaching:
    defaultCache.length === 0
      ? [
          {
            matcher: () => true,
            handler: new NetworkFirst(),
          },
        ]
      : defaultCache,
```

is no longer necessary, fyi :)

> On the other pages It's completely fine to only show the application shell (header and nav) with a message stating that there is no internet connection.

You can create an offline fallback page (let's call it "/~offline"), precache it, and then instruct Serwist to use it as a fallback for pages:

```ts
// next.config.mjs
import withSerwistInit from "@serwist/next";

// You may want to use a more robust revision to cache
// files more efficiently.
// A viable option is `git rev-parse HEAD`.
const revision = crypto.randomUUID();

const withSerwist = withSerwistInit({
  cacheOnNavigation: true,
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  additionalPrecacheEntries: [{ url: "/~offline", revision }],
});
// sw.ts
const serwist = new Serwist({
  // Other options...
  fallbacks: {
    entries: [
      {
        url: "/~offline",
        matcher({ request }) {
          return request.destination === "document";
        },
      },
    ],
  },
});

serwist.addEventListeners();
```

To precache a page and have it handled by `PrecacheStrategy`, add it to `additionalPrecacheEntries`.

To precache a page and still have it handled by whatever `runtimeCaching` strategy that matches it, do this:

```ts
const serwist = new Serwist(options);

const urlsToPrecache = ["/report/new"] as const;

self.addEventListener("install", (event) => {
  const requestPromises = Promise.all(
    urlsToPrecache.map((entry) => {
      serwist.handleRequest({ request: new Request(entry), event });
    }),
  );

  event.waitUntil(requestPromises);
});

serwist.addEventListeners();
```

>  a page with a form

If you use `@serwist/next.defaultCache`, Serwist does not cache POST requests. You will have to add new entries with `method` set to `"POST"`. Just saying, in case you use `<form method="POST">` (with a server action, perhaps) :)

> I also created a ServiceWorker component that I call form my main layout, it currently has the Indexed DB functionality (which give or take works fine) and a useEffect to display an indicator if my app is offline.

Yes, that's fine.

**Comment by guidovizoso** [comment]
Amazing, works like a charm! 🚀  Thank you for your help. I'll close this issue and hopefully can help others in the future!

**Comment by guidovizoso** [comment]
Hi @DuCanhGH, sorry to bother you. After thinking that everything was working correctly I find myself with another issue with this topic so I'm asking for your help again.

I added this code to my service worker:

```ts
const urlsToPrecache = [
  "/",
  "/~offline",
  "/profile",
  "/members",
  "/incidents",
  "/incidents/new",
] as const;

self.addEventListener("install", (event) => {
  const requestPromises = Promise.all(
    urlsToPrecache.map((entry) => {
	// Logs to debug
      console.log("caching", entry);
      const request = serwist.handleRequest({
        request: new Request(entry),
        event,
      });
	// request is undefined
      console.log({ request });
      return request;
    })
  );

  event.waitUntil(requestPromises);
});
```

And at least in development I can see that the requests are undefined:
<img width="728" alt="image" src="https://github.com/user-attachments/assets/95a31022-733f-4d89-8696-1c1141ce673c">

I'm aware that response might be different in dev mode, but neither the fallback page nor the cached entries are navigatable after installing and going offline in the deployed application.

Is there something else I can try, is it a mistake on my part or is something else happening?

Thanks in advance!

**Comment by maiconcarraro** [comment]
@guidovizoso comparing to DuCanhGH example, the `serwist.handleRequest` returns a promise https://github.com/serwist/serwist/blob/d677eede50de2827cf01cf027d4694574efc0f2e/packages/core/src/Serwist.ts#L729

did you try to await/then the result?

**Comment by DuCanhGH** [comment]
@guidovizoso that's... weird. In development mode, when Serwist fails to find a handler, it would tell you before returning, yet I see no logs here. I can't make anything of this much information, I'm afraid.
