### ISSUE TITLE
Enable/Disable runtimeCaching 

### ISSUE THREAD

**Issue by dhamibirendra** [serwist/serwist#172]
Hi, 

Thanks for this awesome project!

I have a peculiar need where I don't want to all the pages once serwist is registered. 

Is there any way to enable/disable caching once serwist is registered? Maybe some function that I can call when I have cached the pages that I need. 

I am using Serwist with NextJs.

Cheer! :)

**Comment by DuCanhGH** [comment]
You can unregister all the routes:

```ts
for (const routes of serwist.routes.values()) {
  for (const route of routes) {
    serwist.unregisterRoute(route);
  }
}
```

...Or you can just not add Serwist's `fetch` and `message` listeners:

```ts
// Instead of this:
serwist.addEventListeners();
// Do this:
self.addEventListener("install", serwist.handleInstall);
self.addEventListener("activate", serwist.handleActivate);
```

**Comment by dhamibirendra** [comment]
Thanks @DuCanhGH , 

Sorry, it seems I was not much clear. 

I have a list of `RuntimeCaching` that I use to cache when I register Serwist and it works well. Once I cache the desired pages, I do not want to cache any pages anymore. 

But, I want to list of `RuntimeCaching` again when I want to cache pages later. So it will be more like a switch so that I can start or stop caching using `RuntimeCaching` list. 

Is there any way to do this?

**Comment by DuCanhGH** [comment]
```ts
import type { PrecacheEntry } from "serwist";
import { ExpirationPlugin, Serwist, StaleWhileRevalidate, Route } from "serwist";

declare const self: ServiceWorkerGlobalScope & {
  // Change this attribute's name to your `injectionPoint`.
  __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
};

let stopCaching = false;

export type CustomStrategyOptions<T extends StrategyOptions> = T & {
  originalStrategy: new (options: T) => Strategy;
}

class CustomStrategy extends Strategy {
  strategy: Strategy;
  constructor(options: CustomStrategyOptions) {
    super(options);
    this.strategy = new options.originalStrategy(options);
  }
  async _handle(request: Request, handler: StrategyHandler): Promise<Response> {
    if (stopCaching) {
      const response = await handler.cacheMatch(request);

      if (!response) {
        return await handler.fetch(request);
      }

      return response;
    }

    return this.strategy._handle(request, handler);
  }
}

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [
    {
      matcher: /\.(?:js)$/i,
      handler: new CustomStrategy({
        cacheName: "static-js-assets",
        plugins: [
          new ExpirationPlugin({
            maxEntries: 48,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          }),
        ],
        originalStrategy: StaleWhileRevalidate,
      }),
    }
  ],
});

self.addEventListener("message", (event) => {
  if (!event.data) return;
  if (event.data.type === "DISABLE_CACHING") {
    stopCaching = true;
  } else if (event.data.type === "ENABLE_CACHING") {
    stopCaching = false;
  }
});

serwist.addEventListeners();
```

It's a bit weird, but it probably works. Note that you cannot use `defaultCache` here (you can, but you will have to modify the snippet a bit). Just copy the array from the source code if you need to.

**Comment by dhamibirendra** [comment]
Hi @DuCanhGH , 

Yeah, this should. How can to know if stopCaching is enabled or disable outside of `sw`? I tried using window.localStorage but window comes undefined inside `sw`

Or is there any way to wait for `window.serwist.messageSW`. I tried using `await` but it blocked everything. 

Thanks :)

**Comment by DuCanhGH** [comment]
@dhamibirendra you should use `await`. I'm not sure what you mean by "it blocked everything" though.

**Comment by dhamibirendra** [comment]
Hi @DuCanhGH, 

I tried adding ` await window.serwist.messageSW(CACHING_MESSAGE.ENABLE_CACHING);` 
But, it keeps on waiting forever and never goes to the next line. However, I can see the the `message` being received in the listener.

**Comment by DuCanhGH** [comment]
@dhamibirendra you have to send a message from the service worker for the promise to settle:

```ts
self.addEventListener("message", (event) => {
  if (!event.data) return;
  if (event.data.type === "DISABLE_CACHING") {
    stopCaching = true;
    event.ports[0]?.postMessage(stopCaching);
  } else if (event.data.type === "ENABLE_CACHING") {
    stopCaching = false;
    event.ports[0]?.postMessage(stopCaching);
  }
});
```

**Comment by dhamibirendra** [comment]
Hi @DuCanhGH , 

Thanks a lot! 
This looks promising and will resolve the issue. Much appreciated :) 

Cheers!

**Comment by DuCanhGH** [comment]
@dhamibirendra please close the issue once it is resolved :)

**Comment by dhamibirendra** [comment]
Many thanks! @DuCanhGH
