### ISSUE TITLE
[Bug]: Next.js App does not work offline

### ISSUE THREAD

**Issue by goleary** [serwist/serwist#173]
### Provide environment information

```
    "next": "^14.2.1",
    "react": "^18.3.0",
    "@serwist/next": "^9.0.5",
    "serwist": "^9.0.5",
```

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/goleary/romad

### To reproduce

[Repo](https://github.com/goleary/romad) is private, but i'm happy to add any investigators to it in order to see the code

`next.config.mjs`:
```js
import withSerwistInit from "@serwist/next";

const withSerwist = withSerwistInit({
  // Note: This is only an example. If you use Pages Router,
  // use something else that works, such as "service-worker/index.ts".
  swSrc: "src/sw.ts",
  swDest: "public/sw.js",
});

export default withSerwist({
  // Your Next.js config
});
```
`src/sw.ts`:
```
import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { Serwist } from "serwist";

// This declares the value of `injectionPoint` to TypeScript.
// `injectionPoint` is the string that will be replaced by the
// actual precache manifest. By default, this string is set to
// `"self.__SW_MANIFEST"`.
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: defaultCache,
});

serwist.addEventListeners();
```

### Describe the bug

After adding my app to the home screen, opening it, turning on airplane mode, force quitting and reopening the app I get a message that says "Safari can't open the page because your iPhone is not connected to the internet".

Here is the deployed app: https://romad-production.up.railway.app/

### Expected behavior

I expect that the app works offline.

### Screenshots (if relevant)

After "Adding to home screen", opening, turning airplane mode on, force quitting and reopening the app:
![image](https://github.com/user-attachments/assets/f1649755-2636-44c0-b960-4bc312194db0)
This is what PWA Builder tells me.
![image](https://github.com/user-attachments/assets/82e617a0-75d4-44ad-86e2-e2640c646b1f)

### Additional information (if relevant)

Perhaps I don't have something set up right? If so, I've reviewed the docs multiple times and I can't figure out what.

**Comment by DuCanhGH** [comment]
Your service worker failed to install:

![image](https://github.com/user-attachments/assets/1b733cf7-4a2d-4b2b-a4ef-f04d4e093511)

This is because Serwist was fed an outdated list of assets to be precached. When it fails to precache an asset for any reason, it throws, causing the whole service worker to be discarded.

Have you checked if your deployment pipeline erroneously cached, or failed to cache, something?

**Comment by goleary** [comment]
Whoops, not sure how that got committed. I removed it!

Now I'm getting this error:
![image](https://github.com/user-attachments/assets/c8bab7bf-d326-4139-8faf-3849a2ca4a1d)


Can I ask where you are seeing those sw.js errors? 

When I load [the site](https://romad-production.up.railway.app/) via Chrome (macOS) or iOS Safari I don't seen any error message in the console (perhaps I resolved that particular error by removing `public/sw.js` from the repo?)

**Comment by goleary** [comment]
Ok, this is strange:

When I navigate to https://romad-production.up.railway.app from Safari on iOS it loads even when offline.

But I "installed" the PWA via Share=>"Add to Home Screen" and this one always shows the error mentioned above when opened after a force quit with no internet :(

**Comment by DuCanhGH** [comment]
That's not the case for me, unfortunately:

![image](https://github.com/user-attachments/assets/087c218d-9356-4ce5-a7f7-d9de1f8ace91)

I guess that this error is because there's not a response in the cache and the network. Perhaps the page was not served by the service worker when you visited said page with network.

**Comment by goleary** [comment]
So strange!

The left devtools is from the homescreen version which has nothing listen under storage even though I loaded the PWA with service before force quitting it. The right is the safari version which does have the assets in the cache.

![image](https://github.com/user-attachments/assets/15ac82ba-df19-47f3-81bd-655e5e679e8e)

I've been trying to find reliable repro steps that do and do not cause the issue, but it is really inconsistent.

This has resulted in the error:

1. Add to home screen
2. Open from home screen
3. Turn off internet
4. Force quit "app"
5. Reopen app

This has also resulted in the error:

1. Add to home screen
2. Open from home screen
3. Background app
4. Force quit "app"
5. Turn off internet
6. Reopen app

And this:

1. Add to home screen
2. Open from home screen
3. Background app
4. Turn off internet
5. Force quit "app"
6. Reopen app

And this:

1. Add to home screen
2. Open from home screen
3. Background app
5. Reopen app
6. Turn off internet
7. Force quit "app"
8. Reopen app

It seems like this is the series of events that most often results in it working correctly, but I've also gotten the error after repeating these steps:
1. Add to home screen
2. Open from home screen
3. Background app
4. Turn off internet
5. **Reopen app (reopening the app without internet before force quitting it)**
6. Force quit "app"
7. Reopen app

FYI: I'm deleting the home screen "app" between every one of these cases.


>I guess that this error is because there's not a response in the cache and the network. Perhaps the page was not served by the service worker when you visited said page with network.
There is only a single page in this app, so I'm not sure how that is possible.


It does seem as though once it works correctly without service after a force quit it continues working correctly every time, so it must be something about the above cases where it doesn't correctly cache the assets, but then once they are they stick around....?

What are the steps you're taking? Where it is working as expected every time?

**Comment by DuCanhGH** [comment]
@goleary 

These are the steps I do:

1. Add app to home screen
1. Open app to install service worker
1. Close app
1. Open app so that the service worker handles the page
1. Close app
1. Turn off internet
1. Open app

Let me know if this works for you :)

**Comment by goleary** [comment]
When you say "Close app" what do you mean? Do you mean background it? or Force quit it?

I just followed those steps assuming you mean Force quit and it does appear as though it works!

That said, the app I'm building is designed to be used off grid (offline), and I'm concerned about how unreliable the offline behavior seems to be in iOS PWAs. That and I'm concerned that I won't be able to get my users to reliably follow the 5 steps required to ensuring that it actually works offline :/ I guess time will tell.

I did come up with a hack to reduce it to 2/3 steps. My app fetches itself after a couple seconds in an attempt to have "the service worker handle the page" without requiring more steps on the part of the user.  This does seem to cut it down to just these steps in order to "reliably" function offline:

1. Add app to home screen
2. Open app to install service worker
3. (wait long enough for app to fetch itself)


Don't know if you have any other ideas about how to "activate" the service worker in a cleaner manner (or perhaps as a part of serwist itself?)

Thanks for all of your help, will close the ticket!

**Comment by goleary** [comment]
also do you mind deleting the image of the map in [this comment](https://github.com/serwist/serwist/issues/173#issuecomment-2262020710)? I need to secure my app, but would like to get that location of off github's permanent record if possible 😉

**Comment by DuCanhGH** [comment]
@goleary 

Add this:

```ts
const serwist = new Serwist(options);

const urlsToPrecache = ["/"] as const;

self.addEventListener("install", (event) => {
  const requestPromises = Promise.all(
    urlsToPrecache.map((entry) => {
      return serwist.handleRequest({ request: new Request(entry), event });
    }),
  );

  event.waitUntil(requestPromises);
});

serwist.addEventListeners();
```

This tells Serwist to cache the pages in `urlsToPrecache` as the service worker is being installed. It works in the same manner as precaching, except that we will not use `PrecacheStrategy`, but rather whatever strategies that match the pages. This works best for Next.js apps, as using `PrecacheStrategy` will cause your pages to be outdated until an updated service worker is installed whenever you deploy an update to your app.

Also there isn't a way to wipe the screenshot off GitHub, I'm afraid. Best you mention your requirements next time, I'd say. Sorry for that :)
