### ISSUE TITLE
[Question] Chrome is treating responses as "opaque" even tho they have correct CORS headers

### ISSUE THREAD

**Issue by MartinPavlik** [serwist/serwist#175]
Hello,

Environment:
```
    "serwist": "^9.0.5",
    "@serwist/next": "^9.0.5",
    "next": "^13.5.0",
```

I'm struggling with opaque responses on images and videos that are being loaded from CDN.

It seems that Chrome always claims that the response is opaque, but when I make the same request using fetch, it normally returns the response and it has response code etc. 

### Serwist logs:
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/a7933340-5b75-45b1-afa9-1071da0376fb">

### Using fetch & console.log:
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/ba5f66f1-755a-4055-9de4-6912b742a068">

It works in a way that I generate an url to our server and then our server responds with 302 request which redirects the browser to S3.

I believe that the 302 request and also the S3 request respond with "acceptable" cors headers for Chrome, but I can't get rid of the "opaque" responses.

The caching is defined like this:

```ts
const customizedCache = [
      // ...
      {
        matcher: ({ sameOrigin, url }) => !sameOrigin && /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i.test(url.pathname),
        handler: new CacheFirst({
          cacheName: 'cross-origin-image-assets',
          plugins: [
            new ExpirationPlugin({
              maxEntries: 64,
              maxAgeSeconds: 2 * 24 * 60 * 60,
              maxAgeFrom: 'last-used',
            }),
          ],
        }),
      },
]

// ...
const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: customizedCache,
});

serwist.addEventListeners();
```

Any idea what can be wrong? The weird thing is that when I perform fetch for the given URL from console using fetch, it returns the response as not opaque, so I suspect it is something related to the service worker...

Thank you for any help! I would really use to have CacheFirst and not NetworkFirst for these assets.

**Comment by MartinPavlik** [comment]
So I found the solution, I suspect that serwist is using fetch with mode: 'no-cors' for requests with different origin?

When I changed the cache policy to:
```ts
      {
        // Note - this needs to be NetworkFirst and not CacheFirst because of the
        // opaque response issue - https://serwist.pages.dev/docs/serwist/runtime-caching
        matcher: ({ sameOrigin, url }) => !sameOrigin && /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i.test(url.pathname),
        handler: new CacheFirst({
          cacheName: 'cross-origin-image-assets',
          fetchOptions: {
            mode: 'cors',
            credentials: 'omit',
          },
          plugins: [
            new ExpirationPlugin({
              maxEntries: 64,
              maxAgeSeconds: 2 * 24 * 60 * 60,
              maxAgeFrom: 'last-used',
            }),
          ],
        }),
      },
  ```
  
 it started working as expected.
 
 
Would it make sense to include this into documentation? It took me almost one day to figure out what was wrong and I found it by an accident more or less - https://stackoverflow.com/questions/35626269/how-to-use-service-worker-to-cache-cross-domain-resources-if-the-response-is-404.

**Comment by DuCanhGH** [comment]
@MartinPavlik sorry for not responding, I was on a vacation and felt it unsuitable to reply to less obvious questions - I usually consult resources to ensure that my information is correct (there's still much to learn about service workers for me, to be honest).

What did you do to invoke the service worker's interception? Usually, you need to set `mode` to `"cors"` for the response to not be opaque. The way you do that depends on how you fetch. If you use a HTML element, such as `<img>`, `<video>`, etc., you will need to set `crossorigin` to `"anonymous"` as mentioned in [the docs on runtime caching](https://serwist.pages.dev/docs/serwist/runtime-caching#cors). If you use `fetch`, set `mode` to `"cors"` as previously mentioned. You may do so via `StrategyOptions.fetchOptions` or `RequestInit`.

**Comment by MartinPavlik** [comment]
@DuCanhGH no worries! 

I read about the `crossorigin` parameter on media tags, but the app I'm trying to make work offline has thousands of lines and to add the HTML property crossorigin to every single img/vdeo tag felt impossible.

So I added `fetchOptions.mode: cors` to every single request to the CDN.

```ts
fetchOptions: {
  mode: 'cors',
  credentials: 'omit',
},
```

Is there some scenario when this could not work?

**Comment by DuCanhGH** [comment]
@MartinPavlik 

> I read about the crossorigin parameter on media tags, but the app I'm trying to make work offline has thousands of lines and to add the HTML property crossorigin to every single img/vdeo tag felt impossible.

Since you use Next.js, I suggest extracting a component :)

> Is there some scenario when this could not work?

Since you set `credentials` to `"omit"`, you may not access any resource that sets `Access-Control-Allow-Origin` to any value other than a single "`*`". Make sure that this route does not match any such resource.
