### ISSUE TITLE
Precache  next/image and redirect issue with next/link

### ISSUE THREAD

**Issue by dhamibirendra** [serwist/serwist#177]
Hi @DuCanhGH , 

Again, thanks a lot for this wonderful library. 

I have two queries as below:

**1. Precache `next/image`**
I am using `<Image> from next/image` for image in my offline pages. Due to some reason the images are not being fetched when I save the page. I tried to precache the image but the path on the page while using `next/image` become dynamic to a format like `/_next/image?url`. How can I precache such images?

**2. URL updating but not refreshing using `next/link`**
When I click on the <Link> from `next/link` on offline page, the URL changes but it doesn't gets redirected to the page. I don't see any error on the console or anything. However, if I change it <Link> with ` window.location.replace` it works well. Is there anyway I can fix this or to debug further?

Thanks!

**Comment by DuCanhGH** [comment]
@dhamibirendra hi :)

> Precache next/image

That's... going to be difficult. Serwist requires that you define the complete URLs of precache assets, meaning that there's no way but to figure said URLs out yourself. They look something like this: ``/_next/image?url=${encodeURIComponent(src)}&w=${width}&q=${quality || 75}${process.env.NEXT_DEPLOYMENT_ID ? `&dpl=${process.env.NEXT_DEPLOYMENT_ID}` : ''}``

> URL updating but not refreshing using next/link

That sounds weird, but not completely unexpected. Maybe `next/link` was fetching something required for the page change, but said `fetch` fails, resulting in the change being dropped. Not sure about this though. It's a complex framework after all :)
