### ISSUE TITLE
[Question] How to ignore query params when caching?

### ISSUE THREAD

**Issue by MartinPavlik** [serwist/serwist#179]
Hi, I'm trying how to find a way to omit query string when caching html pages in next.js app.

The URLs look like this:

```
http://localhost:3000/content?timestamp=1
http://localhost:3000/content?timestamp=2
http://localhost:3000/content?timestamp=3
```

and I would like to tell serwist, that these urls are equal and the content is the same. So to cache it as http://localhost:3000/content by removing the query string.

So something like this code from: https://web.dev/articles/cache-api-quick-guide#retrieving

```ts
const options = {
  ignoreSearch: true,
};

const response = await cache.match(request, options);
```

Any ideas how to do this? Thanks

**Comment by MartinPavlik** [comment]
I came up with this which seems to work, is there some easier way how to do this?

```ts
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (url.pathname === '/content') {
    // Clone the request and remove the query string
    const newUrl = url.origin + url.pathname;
    const newRequest = new Request(newUrl, {
      ...event.request,
    });

    event.respondWith(
      new NetworkFirst({
        cacheName: 'page-live',
        plugins: [
          new ExpirationPlugin({
            maxEntries: 1,
            maxAgeSeconds: 60 * 60,
          }),
        ],
      }).handle({
        event,
        request: newRequest,
        url: new URL(newUrl),
        params: {},
      }),
    );
  }
});
```

**Comment by maiconcarraro** [comment]
@MartinPavlik if you are looking for `ignoreSearch`, its an attribute inside of the `matchOptions`, example:

```js

      new NetworkFirst({
        matchOptions: {
          ignoreSearch: true,
        }
...
```

**Comment by MartinPavlik** [comment]
Thank you! I'm closing this.

**Comment by llz383455526** [comment]
Why ignoreSearch does not work in CacheFirst strategy ?

**Comment by DuCanhGH** [comment]
@llz383455526 what do you mean? It should work just fine.
