### ISSUE TITLE
[Bug]: self.addEventListener for "fetch" not working in sw.ts

### ISSUE THREAD

**Issue by elsigh** [serwist/serwist#18]
### Provide environment information

@DuCanhGH can reproduce locally

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

@DuCanhGH can reproduce locally

### To reproduce

```
self.addEventListener("fetch", (event: FetchEvent) => {
  console.debug(LOG_TAG, "fetch", event.request.url);
});

// Call this in app/sw.ts
self.addEventListener("message", event => {
  console.debug(LOG_TAG, "message me", { event });
});
```

I can make the message event fire but not the fetch event

### Describe the bug

can't capture `fetch`

### Expected behavior

Should be able to capture `fetch`

**Comment by DuCanhGH** [comment]
@elsigh not really. I was reproducing that on Firefox (which I don't do often, mind you - I usually reproduce SW-related stuff on Chromium instead), and found out that I had to go to "about:devtools-toolbox?type=worker&id=SOME_UUID" to see the service worker's logs...

**Comment by elsigh** [comment]
That wasn't it - upgrading to `latest` fixed it for me though!

**Comment by elsigh** [comment]
Basically before:
```
"@serwist/next": "^8.0.5",
    "@serwist/precaching": "^8.0.5",
    "@serwist/sw": "^8.0.5",
```

after
```
    "@serwist/next": "^8.1.1",
    "@serwist/precaching": "^8.1.1",
    "@serwist/sw": "^8.1.1",
```
