### ISSUE TITLE
[Bug]: serwist/next breaks next.js's support for optional chaining

### ISSUE THREAD

**Issue by MartinPavlik** [serwist/serwist#182]
### Provide environment information

```
    "serwist": "^9.0.5",
    "@serwist/next": "^9.0.5",
    "next": "^13.5.0",
```

### Which project is this issue for?

@serwist/window

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

tbd

### To reproduce

Install @serwist/next and then open the next app on Chrome 79 (which does not support optional chaining). The code `node_modules/@serwist/window/dist/index.js` (https://github.com/serwist/serwist/blob/470a72e03a79abc7c929730372bcce31fb486326/packages/window/src/Serwist.ts#L277) contains this code: 
```
if (this._registration?.waiting) {
```
which is included directly into one of the next.js chunks and when Chrome 79 executes this line it throws "Unexpected token ." error.

### Describe the bug

@serwist/next should not break next.js's support for older browsers without optional chaining support.

### Expected behavior

It should not throw an error. So the build of @serwist/window should not contain the optional chaining.

**Comment by DuCanhGH** [comment]
@MartinPavlik Next.js, in its infinite wisdom, decided to not transpile packages in `node_modules`. lol

Add this to your `transpilePackages: ["@serwist/window"]`. With Next.js's default Browserslist configuration, your code will work with Chrome >= 64.

Also, it's not the library's responsibility to support older browsers for you when you have a transpiler. There's no one-size-fits-all way of doing that without some tradeoff (don't be the Node.js 0.4 guy).

**Comment by MartinPavlik** [comment]
Aha, did not know that Next.js stopped transpiling node_modules. Thanks for clarification! The `transpilePackages` helped.

**Comment by DuCanhGH** [comment]
@MartinPavlik I wonder if that's a bug, because that really doesn't seem like what's to be expected. I suggest opening a new issue in Next.js's repo, if you will :)
