### ISSUE TITLE
[Bug]: serwist not working correctly with React 19

### ISSUE THREAD

**Issue by Megaemce** [serwist/serwist#184]
### Provide environment information

Latest Next.js + Latest React + Latest serwist.next

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

localhost:3000

### To reproduce

```json
"dependencies": {
    "@serwist/next": "^9.0.5",
    "next": "^15.0.0-canary.120",
    "react": "^19.0.0-rc-1eaccd82-20240816",
    }
 ````
 
next dev

### Describe the bug

I know that React 19 is still not stable, but it worth noticing that it doesn't support ES modules `require()` anymore thus projects utilizing both newest react and serwist will encounter issues when building:

````powershell
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module [...]\node_modules\@serwist\next\dist\index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at mod.require ([...]\node_modules\next\dist\server\require-hook.js:65:28)
    at [...]\next.config.compiled.js:193:76 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.8.1
````

### Expected behavior

Build to be succesfull

**Comment by Megaemce** [comment]
It seems that actually the issues is cause be cannary Next.js. Maybe it will not be an issue when it will get stable, thus closing for now

**Comment by DuCanhGH** [comment]
@Megaemce 

![image](https://github.com/user-attachments/assets/bf66b4c7-7746-4acb-aa70-a4a90a2d055e)

Are you, by any chance, using next.config.ts? If so, please change it to next.config.mjs.

Well, I'm assuming that's what triggers Next.js to transpile the configuration file, anyway. Nonetheless, this is a bug worth being reported to the Next.js team. ESM-only dependencies like `@serwist/next` won't work with being required by a CommonJS module, which seems to be the format of the transpiled next.config.ts.

**Comment by Megaemce** [comment]
In fact I was as it was a long awaited feature [finally added to cannary version just last month](https://github.com/vercel/next.js/discussions/35969#discussioncomment-10005034). The whole thing about supporting `next.config.ts` by vercel team is a huge disappointment (even tho it's officialy acknolwedge as a go-to on [their website)](https://nextjs.org/docs/pages/building-your-application/configuring/typescript#type-checking-nextconfigts). But that's slicely offtop.

**Comment by DuCanhGH** [comment]
@Megaemce just curious, can I see your next.config.ts?

**Comment by DuCanhGH** [comment]
@Megaemce seems that Next.js is transforming that dynamic import into something that doesn't work. As a workaround, you can change that to a static import declaration:

```ts
import { PHASE_DEVELOPMENT_SERVER, PHASE_PRODUCTION_BUILD } from "next/constants";
import type { NextConfig } from "next";
import withSerwistInit from "@serwist/next";

const withSerwist = withSerwistInit({
   swSrc: "app/sw.ts",
   swDest: "public/sw.js",
});

export default async (phase: string): Promise<NextConfig> => {
  const nextConfig: NextConfig = {
    reactStrictMode: true,
  };
  if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
    // @ts-ignore
    return withSerwist(nextConfig);
  }
  return nextConfig;
};
```

Or, if you are less sane, like I was a few minutes ago, you can also do this:

```ts
// load-serwist.cjs
/**
 * @param {import("next").NextConfig} nextConfig
 */
exports.resolveConfig = async (nextConfig) => {
  const withSerwistInit = (await import("@serwist/next")).default;
  const withSerwist = withSerwistInit({
    // Note: This is only an example. If you use Pages Router,
    // use something else that works, such as "service-worker/index.ts".
    swSrc: "app/sw.ts",
    swDest: "public/sw.js",
  });
  return withSerwist(nextConfig);
};
// next.config.ts
import { PHASE_DEVELOPMENT_SERVER, PHASE_PRODUCTION_BUILD } from "next/constants";
import type { NextConfig } from "next";
// import withSerwistInit from "@serwist/next";
// const withSerwist = withSerwistInit({
//   // Note: This is only an example. If you use Pages Router,
//   // use something else that works, such as "service-worker/index.ts".
//   swSrc: "app/sw.ts",
//   swDest: "public/sw.js",
// });

export default async (phase: string): Promise<NextConfig> => {
  const nextConfig: NextConfig = {
    reactStrictMode: true,
  };
  if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
    // @ts-ignore
    return (await import("./load-serwist.cjs")).resolveConfig(nextConfig);
  }
  return nextConfig;
};
```

Next.js doesn't transpile load-serwist.cjs, so this works. However, it pretty much beats the purpose of even having a next.config.ts anyway, so you should just go and use next.config.mjs :)

**Comment by Megaemce** [comment]
Just FIY, I managed to do that in Next.js 15 (basically React 19) like so:

````ts
import { NextConfig } from "next";
import withSerwistInit from "@serwist/next";
import { PHASE_DEVELOPMENT_SERVER, PHASE_PRODUCTION_BUILD } from "next/constants";


module.exports = async (phase: string) => {
    const nextConfig: NextConfig = {
        reactStrictMode: true,
    }

    if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
        const withSerwist = withSerwistInit({
            // Note: This is only an example. If you use Pages Router,
            // use something else that works, such as "service-worker/index.ts".
            swSrc: "app/sw.ts",
            swDest: "public/sw.js",
        });
        return withSerwist(nextConfig);
    }
    return nextConfig;
};

````
