### ISSUE TITLE
[Docs]: remove runtimeCaching for a specific endpoint

### ISSUE THREAD

**Issue by Sapessii** [serwist/serwist#187]
### Provide environment information

Using latest version on next js 14

### Describe the problem

Hi! I want to prevent the runtime caching on all the endpoints that starts with /api/auth/[auth0].ts, is there a way to do it updating the current defaultCache in next/worker?

### Expected behavior

Exclude some specific path from runtime caching

### Additional information (if relevant)

I've been able to do it but I had to remove all the references to "api" inside the defaultCache and with exclude true here
```
const withSerwist = (await import("@serwist/next")).default({
			swSrc: "src/worker/index.ts",
			swDest: "public/sw.js",
			exclude: [() => true],
		});
```

**Comment by DuCanhGH** [comment]
> I've been able to do it but I had to remove all the references to "api" inside the defaultCache and with exclude true here

😅

You don't need to do that. `exclude` is meant for precaching rather than runtime caching. To prevent runtime caching for all such routes, prepend a network only entry that specifically target those routes:

```js
const routesToFilter = ["/api/foo", "/api/bar"];

const serwist = new Serwist({
  runtimeCaching: [
    {
      matcher({ sameOrigin, url }) {
        return sameOrigin && routesToFilter.includes(url.pathname);
      },
      handler: new NetworkOnly(),
    },
    ...defaultCache,
  ],
});

serwist.addEventListeners();
```

**Comment by Sapessii** [comment]
wow that was super useful! thanks a lot now it's working as expected :)

**Comment by Sapessii** [comment]
Hi @DuCanhGH, hope you are good

Related to this, is it possible to do it also for a server action?

Thank you

**Comment by DuCanhGH** [comment]
@Sapessii server actions are fundamentally just HTTP POST requests, so you can just filter out routes that have server actions. Remember to add `method: "POST"` to each `runtimeCaching` entry you want to match those actions though, otherwise you'll risk filtering out GET requests instead.

**Comment by DuCanhGH** [comment]
@Sapessii server actions are fundamentally just HTTP POST requests, so you can just filter out routes that have server actions. Remember to add `method: "POST"` to each `runtimeCaching` entry you want to match those actions though, otherwise you'll risk filtering out GET requests instead.

**Comment by Sapessii** [comment]
Thank you @DuCanhGH for the fast reply, I have tried with this but is not working

Basically I have a problem with react query where I am prefetching a server action inside the path /messages/{roomId}

Am i doing something wrong? Because using the standard api under /api/chat/messages the bug that I have is not happening

Thank you!

```javascript
const routesToFilter = [
	"/api/auth/login",
	"/api/auth/callback",
	"/api/auth/logout",
	"/api/auth/me",
	"/api/chat/messages",
];

const actionsToFilter = ["/messages/"];

const serwist = new Serwist({
	precacheEntries: self.__SW_MANIFEST,
	skipWaiting: true,
	clientsClaim: true,
	navigationPreload: true,
	runtimeCaching: [
		{
			matcher({ sameOrigin, url }) {
				return sameOrigin && routesToFilter.includes(url.pathname);
			},
			handler: new NetworkOnly(),
		},
		{
			matcher({ sameOrigin, url, request }) {
				return (
					sameOrigin &&
					actionsToFilter.includes(url.pathname) &&
					request.method === "POST"
				);
			},
			handler: new NetworkOnly(),
		},
		...defaultCache,
	],
});

**Comment by DuCanhGH** [comment]
@Sapessii add `method: "POST"` alongside `handler: ...`, `matcher: ...`, etc., not as a check in your `matcher` function.
