### ISSUE TITLE
[Docs]:  @serwist/next (offline) 

### ISSUE THREAD

**Issue by TigMart** [serwist/serwist#201]
### Provide environment information

https://serwist.pages.dev/docs/next

npx degit serwist/serwist/examples/next-basic my-app

### Describe the problem

The code you provided does not work (offline functinality)

### Expected behavior

It must open offline page when i offline but it does not work

### Screenshots (if relevant)

![your-code](https://github.com/user-attachments/assets/c0d22d28-6d23-43ec-9829-f312cc0478ad)
![online](https://github.com/user-attachments/assets/084050ee-cf15-4467-9f2f-2660c7744782)
![offline](https://github.com/user-attachments/assets/b110f5ee-e883-4251-96a3-cec466215e84)

**Comment by DuCanhGH** [comment]
Should be fixed in 9.0.8.
