### ISSUE TITLE
[Bug]: Rollup dependency issue

### ISSUE THREAD

**Issue by brandanking-decently** [serwist/serwist#204]
### Provide environment information

"@serwist/next": "^9.0.8",

### Which project is this issue for?

@serwist/build

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/advisories/GHSA-gcx4-mw62-g8wm

### To reproduce

Install @serwist/next

### Describe the bug

Currently a high severity bug in the rollup package

### Expected behavior

No severities in the package

**Comment by jacktsin1** [comment]
@brandanking-decently @DuCanhGH are there any updates regarding this? Thanks!

**Comment by DuCanhGH** [comment]
It has been a busy September for me, so I'm sorry that I couldn't really focus on Serwist. But this should now be fixed in 9.0.9 :)

**Comment by jeff-soto-od** [comment]
I'm having this same issue, however, when I try to install v9.0.9, it says **no matching target found**. I can also see that there have been 0 downloads on this version since its release 9hrs ago. Is there some caching issue or something here? Not sure why I'm receiving that error
