### ISSUE TITLE
"_rsc" added on the path

### ISSUE THREAD

**Issue by tranhogvien** [serwist/serwist#207]
Hello guys,

I have a problem with the path on offline mode. Everything is fine for a few times, but the path changes with the search parameter "_rsc="
From this:    http://localhost:8080/products
To this:         http://localhost:8080/products?_rsc=fl4ls
And the cached path doesn’t work anymore. I think it’s because the path has changed.
I Googled around and realized it is automatically appended by Next.js. I can't find a way to stop it from being appended to the path.

Do you guys have any ideas about this?
Thank you so much!

**Comment by DuCanhGH** [comment]
> And the cached path doesn’t work anymore. I think it’s because the path has changed.

`@serwist/next`'s `defaultCache` specifies that HTML responses and RSC responses are completely different things. This means that HTML responses go in one cache, and RSC ones another. Please don't change this. Next.js won't know how to handle HTML when it expects RSC.

Not sure why offline doesn't work though. HTML responses are usually enough. When you're offline, Next.js will make a normal browser navigation if it can't fetch RSC.
