### ISSUE TITLE
[Bug]: Fast Refresh Causes Full Reload

### ISSUE THREAD

**Issue by Alipourzadi** [serwist/serwist#208]
## Description
I encountered the same issue as described in #48 . I found a workaround after checking other discussions on related issues in other repositories.

**Packages Version:** 
@serwist/next v9.0.2
@serwist/precaching v9.0.2"
@serwist/sw v9.0.2"
...
next v14.2.5

## Linked Issue
- This issue seems to be related to: [shadowwalker/next-pwa#160](https://github.com/shadowwalker/next-pwa/issues/160)

## Workaround
I found a workaround by following a suggestion from [shadowwalker/next-pwa/issues/160#issuecomment-792072590](https://github.com/shadowwalker/next-pwa/issues/160#issuecomment-792072590):

- Modify the generated ```sw.js``` file and checks if the request is set to use only cached data and is from a different origin.

- code snippet:

```js
...
  let c = (e) =>
    (e.request.cache != "only-if-cached" ||
      e.request.mode !== "same-origin") &&
    new URL(String(e), location.href).href.replace(
      RegExp(`^${location.origin}`),
      "",
    ),
...
```

## Suggested Fix
It might be worth trying a similar approach to resolve this issue.

### Which project is this issue for?

serwist

### To reproduce

Just hit refresh after the first load.

### Describe the bug

Refresh the page endlessly after the first load until the service worker is unregistered and the cache is cleared, or perform a hard refresh (ctrl+shift+r).

### Expected behavior

Refresh as expected 

### Additional information (if relevant)

[#stackoverflow](https://stackoverflow.com/questions/48463483/what-causes-a-failed-to-execute-fetch-on-serviceworkerglobalscope-only-if)

**Comment by DuCanhGH** [comment]
what the hell

> Modify the generated sw.js file and checks if the request is set to use only cached data and is from a different origin.

One great thing about Serwist is that while it abstracts away the pain of setting up a service worker, you are actually in control of the service worker :) So just remove the `serwist.addEventListeners()` line and implement your own listeners.

Besides that, interesting workaround. Not sure why that helps though, if that's just a Chromium bug. I guess I'll have to investigate when I finally get around to working on Serwist in November.

Also, I suppose that we don't really need more than one issue on this bug. So I'm closing this :)
