### ISSUE TITLE
[Bug]: URL Bar Appears in TWA despite Configuration

### ISSUE THREAD

**Issue by Qodestackr** [serwist/serwist#211]
### Provide environment information

Device: Android phone
Browser: Google Chrome (In mobile)
Serwist version: "@serwist/next": "^9.0.8"
Next.js version: "next": "14.1.2",

This issue pertains to the integration of the Serwist framework with my PWA setup(After I moved from `ducanh2912/next-pwa`)

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

http://afyatelemed.com

### To reproduce

I might need to add someone to test users for instance, coz the repo is private.
https://www.afyatelemed.com/.well-known/assetlinks.json (Here is the assetlinks for deep linking though)
1. Downloading from Play
2. Launch the app in a browser or as a TWA.
3. Observe that the URL bar is visible despite configurations meant to hide it.

### Describe the bug

The app is configured to run in standalone mode using the web app manifest, but the URL bar is still displayed when the app is launched as a TWA.

### Expected behavior

The app should launch without displaying the URL bar, providing a full-screen experience similar to a native application.

### Screenshots (if relevant)

![image](https://github.com/user-attachments/assets/6e5ce303-2c1e-4220-bbee-4a2c0cad63af)
![image](https://github.com/user-attachments/assets/42ba6360-24aa-4be2-94d9-ac5c8dbeb6d4)

### Additional information (if relevant)

- I have checked that the manifest file includes the necessary properties and that the service worker is registered correctly.
- The issue persists across different browsers and devices.

*Kindly let me know*. I can share my pwa configuration to see if they actually work. Thanks

**Comment by Qodestackr** [comment]
![image](https://github.com/user-attachments/assets/fa874fde-b3fc-4381-aaf3-571a4c0f2230)

**Comment by DuCanhGH** [comment]
I'm not sure how these issues are related to Serwist, since it only provides you with the tools to build a service worker. Eh, caching issues, perhaps, but seems not the case here.

[Here's a troubleshooting guide from PWABuilder](https://github.com/pwa-builder/CloudAPK/blob/master/Asset-links.md). Seems that you've got a valid assetlinks.json on your hand, so I suppose you can skip to the "Validate your assetlinks.json file" section.

**Comment by Qodestackr** [comment]
Sure let me check around, I was suspecting the same.

**Comment by Qodestackr** [comment]
Let me close this in favor of contacting Play support
