### ISSUE TITLE
[Bug]: dest property instead of swDest in WebpackInjectManifest

### ISSUE THREAD

**Issue by rtritto** [serwist/serwist#25]
### Provide environment information

- @serwist/next: 8.3.0
- @serwist/sw: 8.3.0
- next: 14.0.4
- react: 18.2.0
- react-dom: 18.2.0
- webpack: 5.89.0

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

NA

### To reproduce

- `yarn init -y`
- `yarn set version berry`
- `yarn add next react react-dom @serwist/next @serwist/sw webpack`
- create empty `pages` folder
- create `next.config.mjs`
```ts
import withPWA from '@serwist/next'

const isDev = process.env.NODE_ENV === 'development'

const nextConfig = {}

export default withPWA({
  dest: 'public',
  disable: isDev,
  cacheOnFrontEndNav: true,
  swSrc: 'app/sw.js',
  swDest: 'public/sw.js'
})(nextConfig)
```

- `yarn next build`
```console
   ▲ Next.js 14.0.4
   - Environments: .env

 ✓ (serwist) Compiling for server...
 ✓ (serwist) Compiling for server...
 ✓ (serwist) Compiling for client (static)...
 ○ (serwist) Service worker: C:\<PROJECT_NAME>\public\sw.js
 ○ (serwist)   URL: /sw.js
 ○ (serwist)   Scope: /
Failed to compile.

Please check your InjectManifest plugin configuration:
[WebpackInjectManifest] 'dest' property is not expected to be here. Did you mean property 'swDest'?

Cannot read properties of undefined (reading 'source')
```

### Describe the bug

The build phase fails with error:
```console
Please check your InjectManifest plugin configuration:
[WebpackInjectManifest] 'dest' property is not expected to be here. Did you mean property 'swDest'?

Cannot read properties of undefined (reading 'source')
```

The error should be related to InjectManifest of `@serwist/webpack-plugin`.

### Expected behavior

Build is completed with no errors

**Comment by DuCanhGH** [comment]
Remove `dest: "public"`. It is no longer a valid option.

Full list of changes between `@ducanh2912/next-pwa@9.7.2` and `@serwist/next@8.0.0` are listed [here](https://github.com/serwist/serwist/pull/1).

**Comment by rtritto** [comment]
Worked, thanks!
