### ISSUE TITLE
[Bug]: Webpack config

### ISSUE THREAD

**Issue by rharkor** [serwist/serwist#35]
### Provide environment information

^8.40

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

none

### To reproduce

Add a custom webpack configuration to your nextjs config file

### Describe the bug

This is my webpack config:
```js
webpack: (config) => {
    //? zlib-sync
    config.resolve.fallback = {
      "zlib-sync": false,
      "utf-8-validate": false,
      bufferutil: false,
    }

    return config
  },
 ```
 I need it due to a problem with of another package and next.js (discord.js)
 But your package completly override this so the build doesn't work anymore

### Expected behavior

Take my config before the add your own

**Comment by DuCanhGH** [comment]
That's weird. We do run your `webpack` function before anything else:
![image](https://github.com/serwist/serwist/assets/75556609/adcb67b6-6f7c-49cd-b82e-ebc98a66bad5)
(ignore the red squiggle, it's just me migrating the project to Biome)
Will investigate soon!

**Comment by rharkor** [comment]
Thank's

**Comment by rharkor** [comment]
I solve it by doing this workaround:

```js
  webpack: (config, options) => {
    const newConfig = withSerwist(config).webpack(config, options)
    //? zlib-sync
    newConfig.resolve.fallback = {
      ...newConfig.resolve.fallback,
      "zlib-sync": false,
      "utf-8-validate": false,
      bufferutil: false,
    }

    return newConfig
  },
```

Good to know: I don't find it in your source code but you set a value somewhere for config.resolve.fallback because it is not empty in the output configuration

**Comment by rharkor** [comment]
It return

`{
  process: '/workspaces/discord-bot/node_modules/next/dist/build/polyfills/process.js'
}`

**Comment by DuCanhGH** [comment]
@rharkor that looks like Next.js's doing, rather than Serwist's. If your `config.resolve.fallback` is somehow overridden, that has to be a Next.js issue. This should serve as the proof:
![image](https://github.com/serwist/serwist/assets/75556609/ed28f2dd-94c9-4c86-a66f-3295ba0f4883)

**Comment by rharkor** [comment]
Okay no problem. Thank's you
