### ISSUE TITLE
[Docs]:// Change this attribute's name to your `injectionPoint`.

### ISSUE THREAD

**Issue by SaiRev0** [serwist/serwist#41]
### Provide environment information

Working on Windows with latest versions of nextjs and nodejs

### Describe the problem

I m using the `import type { PrecacheEntry } from '@serwist/precaching'` and there its written that I have to `Change the attribute's name to your 'injectionPoint'.`  And Its throwing error `Cannot find name 'ServiceWorkerGlobalScope'. Did you mean 'ServiceWorkerGlobalScopeEventMap'?ts(2552)`. I m new to PWA and Its my 1st time setting up this, so I don't know what to do. Will be really helpful, if anyone can explain what exactly I have to do ??

### Expected behavior

Dont Know

**Comment by DuCanhGH** [comment]
Change your tsconfig.json:
```json
{
  // Other stuff...
  "compilerOptions": {
    // Other options...
    "types": [
      // Other types...
      // This allows Serwist to type `window.serwist`.
      "@serwist/next/typings"
    ],
    "lib": [
      // Other libs...
      // Add this! Doing so adds WebWorker and ServiceWorker types to the global.
      "webworker"
    ],
  },
}
```
This has been added to the Getting started guide.

**Comment by SaiRev0** [comment]
Thanks a lot man this worked

**Comment by timohausmann** [comment]
I'm also stumbling over this, "Change this attribute's name to your `injectionPoint`" sounds like I have to edit something here, confusing.

**Comment by DuCanhGH** [comment]
@timohausmann https://serwist.pages.dev/docs/build/inject-manifest/configuring

**Comment by timohausmann** [comment]
Okay, after digging a bit, my understanding is, _if_ I would add a custom `injectionPoint` to the Serwist config in `next.config.js` that is different than `"self.__SW_MANIFEST"`, I should also change that accordingly in `sw.ts`.

**Comment by kyeshmz** [comment]
Same stumbling that I did with timo, this should be more clear in the docs.

**Comment by DuCanhGH** [comment]
@kyeshmz well, ideally, I want to get rid of this manual declaration altogether in v9 by making Serwist's framework integration modules export an injection point that Serwist's build tools can pick up and replace with the actual precache manifest, which you can then import as a value and feed to Serwist's service worker APIs. So, basically, instead of making the docs clearer, I want to make the API feel better to use :) Hopefully this can happen.
