### ISSUE TITLE
[Bug]: Ui of the website has issues

### ISSUE THREAD

**Issue by SaiRev0** [serwist/serwist#42]
### Provide environment information

There is a width:100vw defined that is causing this issue; please fix that.

### Which project is this issue for?

None

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://serwist.pages.dev/

### To reproduce

Visit the website

### Describe the bug

width:100vw

### Expected behavior

remove this width

### Screenshots (if relevant)

![image](https://github.com/serwist/serwist/assets/96655163/70786986-3201-412e-a67f-4c75771968c8)

Remove this width:100vw
![image](https://github.com/serwist/serwist/assets/96655163/6ffa7ca7-5ae9-44ca-94b7-9eca50a13ec6)

**Comment by DuCanhGH** [comment]
What the hell is .rootReactVNB? That's not from the docs's CSS.
