### ISSUE TITLE
[Bug]: Serwist is failing to compile for the client if the project has imports of JSON modules

### ISSUE THREAD

**Issue by MarwanAlsoltany** [serwist/serwist#43]
### Provide environment information

Node.js: 20.11
Next.js: 14.04

Used packages:
- `@serwist/sw`
- `@serwist/next`
- `@serwist/precaching`
- `@serwist/build`

Tested all from v8.3.0 to v8.4.2 (some versions had the issue mentioned by #34).

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://codesandbox.io/p/devbox/serwist-json-modules-dg6jz3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr9fcls00007356i8x2u4dwl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr9fcls00002356i5sxhiuk0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr9fcls00004356ih00uxfwd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr9fcls00006356img794hnv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr9fcls00002356i5sxhiuk0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9fcls00001356isrgz3usx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr9fcls00002356i5sxhiuk0%2522%252C%2522activeTabId%2522%253A%2522clr9fcls00001356isrgz3usx%2522%257D%252C%2522clr9fcls00006356img794hnv%2522%253A%257B%2522id%2522%253A%2522clr9fcls00006356img794hnv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9fcls00005356i3if10me6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr9fcls00005356i3if10me6%2522%257D%252C%2522clr9fcls00004356ih00uxfwd%2522%253A%257B%2522id%2522%253A%2522clr9fcls00004356ih00uxfwd%2522%252C%2522activeTabId%2522%253A%2522clr9fcs5i004x356ik7xuh1xp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9fcls00003356i9swj7rju%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr9fcs5i004x356ik7xuh1xp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr9fcsqg00b5eege5rim9243%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To reproduce

NOTE: I couldn't reproduce the issue on the provided sandbox.

Here is some context in case it helps: 
My app is pretty complex and has a lot of modules and abstractions. The take is, I have localizations files in JSON formats that are provided to the client by a provider via a server component to handle translations on the client side. These JSON files are added to  the built assets at the end, are thus are part of the client code. When building the app, Serwist is complaining about these file because webpack fails to parse the files (see screenshots below).

### Describe the bug

If JSON modules are imported and are part of the build, webpack parser fails. From my research online, the issue may have to do with webpack JSON loader.

BTW, "(serwist) Compiling for server" is finishing successfully, but "Compiling for client (static)..." is failing.

### Expected behavior

The app should be built as expected (when disabling Serwist via configuration, the app is built successfully)

### Screenshots (if relevant)

![image](https://github.com/serwist/serwist/assets/7969982/f2ec28cc-2ee8-4ddf-9e0f-3de163893c0f)
![image](https://github.com/serwist/serwist/assets/7969982/7b4fc454-8d20-4905-ab44-bf20cf503916)

**Comment by DuCanhGH** [comment]
Right, disabling Serwist works, but I don't see how that means this is related to it. This issue just screams Next.js or Webpack because there's nothing in `@serwist/webpack-plugin` that can cause such a horrendous issue. I don't think it is really related to JSON modules, since you, too, can't reproduce it. Maybe you should try removing the JSON modules to verify, if that's possible? Perhaps there's some deeper issues with your actual app, but I don't have access to it so here we are.

P/s: I don't see why you have to hide the JSON part to be honest. It ends up in the client bundle anyway, so there shouldn't be any secret in it, should there?

**Comment by DuCanhGH** [comment]
@MarwanAlsoltany huh, now that you have narrowed down the issue, would a reproduction be possible? I'd really appreciate it, since there's nothing much I can do if there's nothing to experiment with...

**Comment by MarwanAlsoltany** [comment]
@DuCanhGH I tried to reproduce the issue in the Sandbox, but unfortunately I couldn't get it to throw the same error I was getting. I will close this issue, as there is no way to know what really went wrong (maybe someone in the future stumbles upon the issue and can reproduce it). Thanks for taking the time to look into it, though.
