### ISSUE TITLE
[Bug]: Missing `webpack` dependency

### ISSUE THREAD

**Issue by rtritto** [serwist/serwist#5]
### Provide environment information

@serwist/next: 8.0.2
@serwist/webpack-plugin: 8.0.2

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

NA

### To reproduce

1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add @serwist/next @serwist/webpack-plugin next react react-dom`
4. See yarn log

### Describe the bug

Missing `webpack` dependency from `@serwist/next` and `@serwist/webpack-plugin`

```console
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @serwist/next@npm:8.0.2, @serwist/webpack-plugin@npm:8.0.2, next@npm:14.0.4, and 208 more.
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ <PROJECT_NAME>@workspace:. doesn't provide webpack (p1fed5), requested by @serwist/next.
➤ YN0002: │ <PROJECT_NAME>@workspace:. doesn't provide webpack (pc79a1), requested by @serwist/webpack-plugin.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings
```

### Expected behavior

No warnings in log

### Additional information (if relevant)

Workaround:
add in `.yarnrc.yml`
```yml
packageExtensions:
  "@serwist/next@*":
    dependencies:
      webpack: "*"
  "@serwist/webpack-plugin@*":
    dependencies:
      webpack: "*"
```

**Comment by DuCanhGH** [comment]
```
➤ YN0002: │ <PROJECT_NAME>@workspace:. doesn't provide webpack (p1fed5), requested by @serwist/next.
➤ YN0002: │ <PROJECT_NAME>@workspace:. doesn't provide webpack (pc79a1), requested by @serwist/webpack-plugin.
```
These are the warnings :) You have to install all `peerDependencies`, or run the risk that something won't work. An additional manual check is possible, but I don't find it necessary.

**Comment by rtritto** [comment]
Sorry, I didn't check the related peer dependencies.
