### ISSUE TITLE
[Bug]: serwist/next using `basePath` results in wrong sw.js URL in manifest

### ISSUE THREAD

**Issue by msanguineti** [serwist/serwist#55]
### Provide environment information

```pre
"@serwist/next": "^8.4.3",
"@serwist/precaching": "^8.4.3",
"@serwist/sw": "^8.4.3",
"next": "^14.1.0",
```

Next.JS is using the app router and source is in `app/src`

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/msanguineti/next-pwa-test

### To reproduce

- add `output: 'export'` to next.config options
- add `basePath` to next.config options
- run `npm run build` to get static files for a website under `out/`
- check the injected precache manifest found in `out/sw.js`

### Describe the bug

The URL for the service worker (default `sw.js`) is wrongly injected in the manifest, an extra `_next/../public/` path is found there:

```js
...
precacheEntries: [
    {
      revision: "71782f0a19e1ac2b7126fa129afe790b",
      url: "/next-pwa-test/_next/../public/sw.js",
    },
   ...
]
...
```

### Expected behavior

This is what I should expect:

```js
...
precacheEntries: [
    {
      revision: "71782f0a19e1ac2b7126fa129afe790b",
      url: "/next-pwa-test/sw.js",
    },
   ...
]
...
```

### Additional information (if relevant)

If I don't use `basePath`, the plugin correctly inject the service worker path.

I found this in the source code:

https://github.com/serwist/serwist/blob/13d6b75b2dec7fa161e33f0cec91bd4fe4dc09ca/packages/next/src/index.ts#L198-L201

This is probably done to remove the extra fluff path `/_next/../public/` generated. But when using `basePath` this substitution does not match and the extra path is not removed.

I also tried to use `swUrl` but it has no effect whatsoever, even setting `swUrl` to something crazy:

```pre
...
swDest: "public/sw.js"
swUrl: "in/the/middle/of/nowhere/unserviceable-worker.js"
...
```

nothing happens, the service worker is always injected at `[basePath]/_next/../public/sw.js`

To solve the issue I resorted to use manifest transformations in `next.config.js`:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  basePath: '/next-pwa-test',
}


/** @type {import("@serwist/build").ManifestTransform}  */
const manifestTransforms = async (manifestEntries) => {
  const manifest = manifestEntries.map((m) => {
    m.url = m.url.replace("/_next/../public/", "/");
    return m;
  });
  return { manifest, warnings: [] };
}

/** @type {import("@serwist/next")} */
const withSerwist = require("@serwist/next").default({
  swSrc: "src/app/sw.ts",
  swDest: "public/sw.js",
  manifestTransforms: [manifestTransforms],
});

module.exports = withSerwist({
  ...nextConfig,
});
```

**Comment by DuCanhGH** [comment]
Bloody hell 💀
Thanks for investigating! What you provided was detailed, informative, and helpful. Will fix this and add a test soon!

**Comment by DuCanhGH** [comment]
@msanguineti 8.4.4 has been released. Give it a try!

**Comment by msanguineti** [comment]
> @msanguineti 8.4.4 has been released. Give it a try!

Yep, it seems OK! Thanks a lot for the quick release.
