### ISSUE TITLE
[Bug]: PPR Forces Load Wait

### ISSUE THREAD

**Issue by versecafe** [serwist/serwist#58]
### Provide environment information

OS: MacOS Sonoma
Chip: M3 Pro

Server Runtime: Node 18 LTS
Next Version: 14.1.1-canary.2
Serwist SW & Serwist Next: @latest

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/versecafe/serwist-ppr-issue-demo

### To reproduce

1. Make a nextJS project with serwist
2. add PPR and a suspense boundary to main page
3. set as a PWA
4. launch PWA

### Describe the bug

When using PPR PWA loads until all content is fetched.

### Expected behavior

Should load the HTML shell around suspense boundaries and stream in the new content, same as behaviour when visiting the base web version.

### Screenshots (if relevant)

<img width="469" alt="image" src="https://github.com/serwist/serwist/assets/147033096/33c93992-dc46-40e9-85ac-abe7b6055582">

### Additional information (if relevant)

This may just be an issue with PPR or the PWA spec rather than serwist in which case just let me know and I'll remove this.

**Comment by DuCanhGH** [comment]
When a user launches your PWA from the home screen, a splash screen is displayed until the PWA is ready. Seems that changing the behaviour doesn't seem to be possible, unfortunately.

**Comment by versecafe** [comment]
> When a user launches your PWA from the home screen, a splash screen is displayed until the PWA is ready. Seems that changing the behaviour doesn't seem to be possible, unfortunately.

Unfortunate, I have found a workaround of immediately redirecting them to a new page as PPR functions fine so long as it is not the base page of the PWA but it's a bit annoying

**Comment by DuCanhGH** [comment]
@versecafe cool. That seems to work, so you do you :) There doesn't seem to be another solution...
