### ISSUE TITLE
[Feature request]: Offline page fallback

### ISSUE THREAD

**Issue by vshellrmr** [serwist/serwist#64]
### Which project is this feature request for?

@serwist/next

### Describe the feature you'd like to request

It would be good to use offline page fallback support

### Describe the solution you'd like

https://github.com/shadowwalker/next-pwa?tab=readme-ov-file#offline-fallbacks

### Describe alternatives you've considered

https://github.com/shadowwalker/next-pwa

**Comment by DuCanhGH** [comment]
```ts
installSerwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: defaultCache,
  fallbacks: {
    entries: [
      {
        url: "/~offline",
        revision,
        matcher({ request }) {
          return request.destination === "document";
        },
      },
    ],
  },
});
```

**Comment by magnattic** [comment]
I just tried to get this to work in serwist's "next-basic" example app, but for me the offline page doesn't show up when I go offline. Tried it on iPad by disabling Wifi and on Desktop Chrome by disabling network in dev tools.

Is there a trick, am I testing this wrong or is this not configured correctly in the example app?

What I did:
> npx create-next-app@latest -e https://github.com/serwist/serwist/tree/main/examples/next-basic
> yarn install
> yarn dev
> connect with browser
> install pwa
> disable network

I also tried to add a Link to a second page, thinking maybe the offline page only shows up during navigation.

What happens instead off ~offline:
I get cached content where available, otherwise I get the browsers "This site can’t be reached".

**Comment by vshellrmr** [comment]
@magnatticI also encountered this problem while testing my application. @DuCanhGH are there any other nuances in the config?

**Comment by vshellrmr** [comment]
@magnattic also encountered this problem while testing my application. @DuCanhGH are there any other nuances in the config?

**Comment by vshellrmr** [comment]
> I just tried to get this to work in serwist's "next-basic" example app, but for me the offline page doesn't show up when I go offline. Tried it on iPad by disabling Wifi and on Desktop Chrome by disabling network in dev tools.
> 
> Is there a trick, am I testing this wrong or is this not configured correctly in the example app?
> 
> What I did:
> 
> > npx create-next-app@latest -e https://github.com/serwist/serwist/tree/main/examples/next-basic
> > yarn install
> > yarn dev
> > connect with browser
> > install pwa
> > disable network
> 
> I also tried to add a Link to a second page, thinking maybe the offline page only shows up during navigation.
> 
> What happens instead off ~offline: I get cached content where available, otherwise I get the browsers "This site can’t be reached".

@magnattic also encountered this problem while testing my application. @DuCanhGH are there any other nuances in the config?

**Comment by DuCanhGH** [comment]
@vshellrmr most likely, no, there's nothing more to be done. Wondering how this can happen, but I'm guessing that our example's `matcher` doesn't actually work. It is possible that `request.destination` isn't actually `"document"`. If anything else, we'd need a bit more investigation.
