### ISSUE TITLE
Cannot find package 'webpack'

### ISSUE THREAD

**Issue by Hemistone** [serwist/serwist#88]
I got error `Cannot find package 'webpack'` and I assume you've missed to add `npm i -D webpack` in the installation part of getting started, since I've found difference on the former package([@ducanh2912/next-pwa](https://ducanh-next-pwa.vercel.app/docs/next-pwa/getting-started#install) - ex `npm i @ducanh2912/next-pwa && npm i -D webpack`).

https://github.com/serwist/serwist/blob/36f780c5fb401cadafb06b77a8cd30cdcb274689/docs/src/routes/(vertical)/docs/next/getting-started/%2Bpage.server.ts#L18-L33

If you think this is true, maybe I can add several code lines in the docs thorough PR.

**Comment by DuCanhGH** [comment]
![image](https://github.com/serwist/serwist/assets/75556609/d20961f6-a0a1-458a-94d3-69d0578f4249)
Well I had assumed that your average package manager would warn you of that.
A PR would be nice. Thanks!

**Comment by Hemistone** [comment]
Thx! I'm looking forward to the next major version release 😉
