### ISSUE TITLE
[Bug]:  require() of ES Module not supported when running tests

### ISSUE THREAD

**Issue by hirviid** [serwist/serwist#92]
### Provide environment information

- Serwist: 8.4.4
- Next: 14.0.4
- Node: 20.10.0

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/hirviid/serwist-next-jest-example

### To reproduce

- Clone https://github.com/hirviid/serwist-next-jest-example
- Run `yarn`
- Run `yarn test`

### Describe the bug

Running Jest after adding @serwest/next to a nextjs gives an error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ~/serwist-example-next/node_modules/string-width/index.js from ~/serwist-example-next/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in ~/serwist-example-next/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (~/serwist-example-next/node_modules/cliui/build/index.cjs:291:21)
error Command failed with exit code 1.
```

### Expected behavior

Adding Serwist to a Next project should not impact Jest tests.

**Comment by DuCanhGH** [comment]
That seems to be a Jest issue:

![pnpm tree](https://github.com/serwist/serwist/assets/75556609/eed221f6-72c0-4265-8cd8-9aea1c98e0be)

![yarn stable tree](https://github.com/serwist/serwist/assets/75556609/0ce042cd-8c0b-4b3d-94f0-b0862894b23c)

Not sure how this could be attributed to Serwist when the traceback didn't even refer to it.

Also, I couldn't reproduce this in Yarn stable, pnpm, or npm. This issue only appeared when I tried Yarn v1 (same as the original reproduction). Just saying, but you shouldn't use it anymore in 2024.

**Comment by hirviid** [comment]
Hi @DuCanhGH, thanks a lot for your quick answer.

Indeed, the traceback doesn't mention anything about Serwist, but the issue occurs only after adding Serwist packages.

I tested it with npm and it works indeed, so I guess it's some strange Yarn v1 issue, and we need to migrate 😉

Thanks again for your quick and complete reply! 🙌

**Comment by DuCanhGH** [comment]
@hirviid glad to hear that! Sometimes I do wish that Yarn v1 weren't such a cheeky little undead bastard that keeps on haunting the community... Strange things.
