### ISSUE TITLE
[Bug]: Next pages navigation causes stale data

### ISSUE THREAD

**Issue by paales** [serwist/serwist#94]
### Provide environment information

- @serwist/next

### Which project is this issue for?

None

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

-

### To reproduce

- Navigate over a nextjs project but have the pages revalidate in the background.

### Describe the bug

A regular page loads as it is using this configuration: https://github.com/serwist/serwist/blob/main/packages/next/src/index.browser.ts#L188-L198

But you get old data when using the 'ajax call':
https://github.com/serwist/serwist/blob/main/packages/next/src/index.browser.ts#L117-L127

### Expected behavior

We've currently set it to NetworkFirst to handle this case, that solves the issue.

**Comment by DuCanhGH** [comment]
Please update to Serwist preview for now. This bug has been fixed there :)
