### ISSUE TITLE
[Bug]: Service Worker is installed on a page out of scope.

### ISSUE THREAD

**Issue by hig4** [serwist/serwist#99]
### Provide environment information

"@serwist/next": "^8.4.4",
"@serwist/precaching": "^8.4.4",
"@serwist/sw": "^8.4.4",

### Which project is this issue for?

@serwist/next

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

None

### To reproduce

next.config.(m)js:
```
  swUrl: "/app/sw.js",
  scope: "/app/",
```

Then access to `/`.

### Describe the bug

If I set `scope` to `/app/` and `swUrl` to `/app/sw.js` in next.config.(m)js, the sw.js is installed when I opened the page `/`.

### Expected behavior

sw.js is not installed on a page out of scope.

### Screenshots (if relevant)

![image](https://github.com/serwist/serwist/assets/10399371/2fb79f56-ad55-45c9-8baa-1fef5232751e)

### Additional information (if relevant)

Setting `register` to `false` in next.config.(m)js and calling `window.serwist.register()` manually is a workaround.

**Comment by DuCanhGH** [comment]
The current behaviour of  `register` unconditionally calls `window.serwist.register()`. That doesn't affect out-of-scope pages though. Still, I'd like to get rid of these warnings. What do you suggest for a change? Shall we check if the current page's `pathname` starts with `scope`?

**Comment by hig4** [comment]
It should be checked that the current page is within the `scope`, I think. Are there any negative side effects or imcompatibilitites for existing codes?

**Comment by DuCanhGH** [comment]
@hig4 can't see any side effects. Also, we have already implemented quite a few breaking changes in v9.0.0 anyway, so it shouldn't be a problem...
